/*--------------------------------------------------------------------------+
| Macro Name    : tu_header.sas
|
| Macro Version : 6 build 1
|
| SAS version   : SAS v8.2
|
| Created By    : Shan Lee
|
| Date          : 21-May-2003
|
| Macro Purpose : Generate SAS title statements required to produce the
|                 header of the data display. The text for the first
|                 three title statements will be generated by this macro,
|                 based upon values of global macro variables that indicate
|                 the study identifier, study description, population etc,
|                 whereas the text for any other title statements is
|                 simply user specified verbatim text.
|                 This macro also generates a global macro variable to indicate
|                 the actual number of title lines that are used in the
|                 header.
|
| Macro Design  : Procedure style
|
| Input Parameters :
|
| NAME           DESCRIPTION                              REQ/OPT   DEFAULT
|
| CELLINDX       Indicates whether or not header will be  Req       N
|                generated for a cell index.
|
| Output: SAS title statements for the listing/table/cell index.
|
| Global macro variables created: G_HEADER0
|
|
| Macros called :
|  (@)tr_putlocals
|  (@)tu_putglobals
|  (@)tu_abort
|
| Example:
| %tu_header(cellindx = Y)
|
|
| **************************************************************************
| Change Log :
|
| Modified By :             Andrew Ratcliffe
| Date of Modification :    05-AUG-2003
| New Version Number :      1.0 / 2
| Modification ID :         ABR01
| Reason For Modification : Derive g_header0 properly when no title4.
|                           Set options nodate.
|                           Do not prefix g_popdata with ardata.
|                           Check dsid when opening datasets.
|                           In addition to creating L_POP, create l_popNAME
|                            and l_popLABEL. Use these in comparisons for
|                            pop/subpop/poplbl checks.
|
| Modified By :             Andrew Ratcliffe
| Date of Modification :    12-AUG-2003
| New Version Number :      1.0 / 3
| Modification ID :         ABR02
| Reason For Modification : Use appropriate quoting for g_poplbl.
|                           Create extra local macro variable to store the
|                            label with "population" removed. The new variable
|                            is named l_popLabelNoPop and is used in comparisons
|                            for pop/subpop/poplbl checks.
|
| Modified By :             Shan Lee
| Date of Modification :    25-Sep-2003
| New Version Number :      1/4
| Modification ID :         SL001
| Reason For Modification : Do not show the STATUS after the data display
|                           number - if the user wishes to indicate that a
|                           data display is in the draft stage, then the
|                           R_STUDY_DESC parameter of the ts_setup macro
|                           should include text to indicate this.
|
| Modified By :             Yongwei Wang
| Date of Modification :    12-MAR-2004
| New Version Number :      2/1
| Modification ID :         YW001
| Reason For Modification : Added %upcase() to &G_STUDY_ID in the title to
|                           make the study ID upcase.
|
| Modified By :             Shan Lee
| Date of Modification :    12-Mar-2004
| New Version Number :      3/1
| Modification ID :         SL002
| Reason For Modification : Incorporate amendments specified in change
|                           control form HRT0003 - ie take account of new
|                           display types. Also, ensure that all calls to
|                           tu_abort are conditional on g_abort being set
|                           to 1, to avoid cluttering the log unnecessarily.
|                           A call to tu_abort will be placed after the
|                           parameter validation, so the call to tu_abort that
|                           appears at the end of the macro, after the normal
|                           processing, can be removed.
|
| Modified By :             John King
| Date of Modification :    02-Nov-2004
| New Version Number :      4/1
| Modification ID :         JK001
| Reason For Modification : Incorporate amendments specified in change
|                           control form HRT0051 - use SAS/GRAPH title
|                           statement options to justfiy titles 1 and 2 when
|                           G_DSPLYTYP=F.
|     
| Modified By :             Shan Lee
| Date of Modification :    15-Jul-2008
| New Version Number :      5/1
| Modification ID :         SL003
| Reason For Modification : Incorporate amendments specified in change
|                           control forms HRT0133 and HRT0208
|                           HRT0133: allow additional valid values for g_dsplytyp
|                           HRT0208: apply macro quoting to L_TITLE2.
|
| Modified By :             Shivam Kumar
| Date of Modification :    21-OCT-2013
| New Version Number :      6/1
| Modification ID :        
| Reason For Modification : Replace local macro variable sysmsg with l_sysmsg
|
+----------------------------------------------------------------------------*/
%MACRO tu_header(
  cellindx = N  /* Is header being generated for cell index? */
                );
/*
/ Echo values of parameters and global macro variables to the log.
/----------------------------------------------------------------------------*/
%local MacroVersion;
%let MacroVersion = 6 build 1;
%include "&g_refdata/tr_putlocals.sas";
%tu_putglobals(varsin = g_study_id g_study_desc g_popdata g_pop g_poplbl
                        g_subpop g_dsplytyp g_dsplynum g_datadate
                        g_title1 g_title2 g_title3 g_title4 g_title5 g_title6
                        g_title7 g_ls)                              /* SL001 */
/*
/ Declare local macro variables that will be used during the parameter
/ validation and throughout the remainder of this macro.
/
/ L_POP          Label/name of the decoded population variable.
/ L_POPNAME      Name of (de)coded population variable.
/ L_POPLABEL     Label of (de)coded population variable.
/ LEN            Length of text.
/ SUFFIX         Last 2 characters of name of population variable.
/ DSID           Indentifier of dataset opened by SYSFUNC.
/ RC             Return code from closing dataset.
/ L_SYSMSG       Value returned by SYSMSG function.
/ POP_VARLBL     Label of population variable.
/ L_TITLE1       Text for title1 statement.
/ L_TITLE2       Test for title2 statement, minus date of data.
/ NUM_SPACES     Number of blank spaces required to pad text for title to end
/                of line.
/ N              Counter used for DO loop processing.
/ RIGHT_TEXT     Text appearing on right of second title, ie date of data.
/ FIG_LIST_TAB_CELL  Localised text indicating whether output is for figure,
/                    listing, table or cell index.
/ DDMM_TITLE_NUM Number of DDMM title corresponding to the SAS title that is
/                currently being generated.
/ RX             Used for RX functions and call routines.
/ TIMES          Used for RX functions and call routines.
/----------------------------------------------------------------------------*/
%local l_pop
       l_popName l_popLabel l_popLabelNoPop /* ABR01 ABR02 */
       len suffix dsid rc
       l_sysmsg  /* ABR01 */
       pop_varlbl l_title1 l_title2 num_spaces n
       right_text fig_list_tab_cell ddmm_title_num rx times;        /* SL002 */
/*
/ PARAMETER VALIDATION
/----------------------------------------------------------------------------*/
/*
/ Check that CELLINDX is either N or Y.
/----------------------------------------------------------------------------*/
%let cellindx = %nrbquote(%upcase(%substr(%nrbquote(&cellindx), 1, 1)));
%if &cellindx ne N and &cellindx ne Y %then
%do;
  %put %str(RTE)RROR: TU_HEADER: CELLINDX should be either N or Y.;
  %let g_abort = 1;                                                 /* SL002 */
%end;
/*
/ Check that G_STUDY_ID is not missing.
/----------------------------------------------------------------------------*/
%if %nrbquote(&g_study_id) eq %then
%do;
  %put %str(RTE)RROR: TU_HEADER: Study identifier has not been specified.;
  %let g_abort = 1;                                                 /* SL002 */
%end;
/*
/ Parameter validation of G_POP, G_SUBPOP, and G_POPLBL.
/
/ Please note that in the 4 bullet points below, the "label/name of the
/ decoded population variable" is obtained as follows -  Resolve g_pop to
/ obtain the name of the coded population variable, and remove the "cd" at
/ the end of this name to give the name of the decoded population variable.
/ Next, obtain the label that is associated with the decoded population
/ variable in the dataset given by resolving g_popdata. If there is no label
/ associated with the decoded population variable, then use the variable name
/ itself.
/
/ -> If g_pop is present, and g_subpop is missing, then generate an RTNOTE if
/    g_poplbl is missing (if g_poplbl is missing, then it will default to
/    the label/name of the decoded population variable).
/
/ -> If g_pop is missing, and g_subpop is present, then generate an RTWARNING
/    if g_poplbl is missing or "All subjects" (if this is true, then we shall
/    set g_poplbl to "All subjects" (or some localised equivalent)
/    concatenated with g_subpop).
/
/ -> If g_pop is present, and g_subpop is present, then generate an RTWARNING
/    if g_poplbl is either missing or equal to the label/name of the decoded
/    popoulation variable (in either of these scenarios that generate an
/    RTWARNING, g_poplbl will default to the label/name of the decoded
/    population variable, concatenated with g_subpop).
/    ABR02 - Note that the label in this scenario could be with or without the
/            localised word "population". The comparison must be made with
/            both forms.
/
/ -> If g_pop is missing, and g_subpop is missing, then generate an RTNOTE if
/    g_poplbl is missing (in this scenario, g_poplbl will default to "All
/    Subjects", or some localised equivalent).
/
/----------------------------------------------------------------------------*/
/*
/ Store the "label/name of the decoded population variable" (as defined above)
/ in the local macro variable L_POP.
/ ABR01 - Also store varname of (de)coded var in / l_popName and var label
/         in l_popLabel.
/ ABR02 - Also store label without localised "population" in l_popLabelNoPop.
/
/ This will be achieved in 2 stages: First, set L_POP to the name of the
/ decoded population variable (if the decoded population variable can not be
/ obtained, then set L_POP to be the coded population variable whose name is
/ given by resolving G_POP). Second, if a dataset label can be obtained for
/ L_POP, then reset L_POP to be this label, otherwise, leave as is.
/
/ Note that the set up macro will already have checked that the dataset
/ variable represented by G_POP exists in the dataset represented in G_POPDATA.
/----------------------------------------------------------------------------*/
%let l_pop = %nrbquote(&g_pop);
%let dsid = %sysfunc(open(&g_popdata));      /* ABR01 */
/* ABR01 - Check that it opened okay */
%if &dsid le 0 %then
%do;
  %let l_sysmsg = %sysfunc(sysmsg());
  %put %str(RTE)RROR: &sysmacroname: Could not open POPDATA (&g_popdata);
  %put %str(RTN)OTE: &sysmacroname: Message from SAS was: &l_sysmsg;
  %let g_abort = 1;                                                 /* SL002 */
%end;
%if %length(&l_pop) gt 0 %then     /* ABR01 */
%do;
  %let len = %length(&l_pop);
  %let suffix = %nrbquote(%upcase(%substr(&l_pop, &len - 1)));
  %if &suffix eq CD %then
  %do;
    %if %sysfunc(varnum(&dsid, %substr(&l_pop, 1, &len -2))) %then
    %do;
      %let l_pop = %substr(&l_pop, 1, &len - 2);
    %end;
  %end; /* %if &suffix eq CD %then */
  %let l_popName = &l_pop;    /* ABR01 */
        /* Default value for popLabel */
  %let l_popLabel = &l_popName;  /* ABR02 */
  %let pop_varlbl = %sysfunc(varlabel(&dsid, %sysfunc(varnum(&dsid, &l_pop))));
  %if %nrbquote(&pop_varlbl) ne %then
  %do;
    %let l_pop = %nrbquote(&pop_varlbl);    /* ABR02 */
    %let l_popLabel = &l_pop;
    /* ABR02 - Now remove localised "population" to create l_popLabelNoPop */
    %let l_popLabelNoPop = &l_popLabel;
    %let rx = %sysfunc(rxparse(%sysfunc(putc(POPULATION, $local.)) TO ));
    %let times = 999;
    %syscall rxchange(rx, times, l_popLabelNoPop);
    %syscall rxfree(rx);
  %end;
  %let rc = %sysfunc(close(&dsid));
%end; /* %if %length(&l_pop) gt 0 %then */
/*
/ The value of the  global macro variable G_POPLBL will be re-set by this
/ macro under certain circumstances.
/ A macro quoting function will be applied to this global macro variable, so
/ that it does not need to be quoted in every macro IF ... THEN statement.
/ This same technique (quoting a global macro variable in a %LET statement,
/ will not be aplied to other global macro variables, since we do not want to
/ alter a global macro variable in any way unless values have to be
/ assigned to it by this macro.
/----------------------------------------------------------------------------*/
%let g_poplbl = %nrbquote(&g_poplbl);
/*
/ G_POP present, G_SUBPOP missing
/----------------------------------------------------------------------------*/
%if %nrbquote(&g_pop) ne and %nrbquote(&g_subpop) eq %then
%do;
  %if &g_poplbl eq %then
  %do;
    %put %str(RTN)OTE: TU_HEADER: Population label has not been specified so default value will be used.;
    %let g_poplbl = &l_pop;
  %end;
%end; /* %if %nrbquote(&g_pop) ne and %nrbquote(&g_subpop) eq %then */
/*
/ G_POP missing, G_SUBPOP present
/----------------------------------------------------------------------------*/
%if %nrbquote(&g_pop) eq and %nrbquote(&g_subpop) ne %then
%do;
  %if &g_poplbl eq %then
  %do;
    %put %str(RTW)ARNING: TU_HEADER: Population subset has been specified, but population label has not been specified.;
    %put %str(RTN)OTE: TU_HEADER: Population label will be re-assigned.;
    %let g_poplbl = %sysfunc(putc(ALL SUBJECTS, $local.));
    %let g_poplbl = &g_poplbl &g_subpop;
  %end;
  %if &g_poplbl eq %sysfunc(putc(ALL SUBJECTS, $local.)) %then
  %do;
    %put %str(RTW)ARNING: TU_HEADER: Population subset has been specified, but population label states "All Subjects".;
    %put %str(RTN)OTE: TU_HEADER: Population label will be re-assigned.;
    %let g_poplbl = %sysfunc(putc(ALL SUBJECTS, $local.));
    %let g_poplbl = &g_poplbl &g_subpop;
  %end;
%end; /* %if %nrbquote(&g_pop) eq and %nrbquote(&g_subpop) ne %then */
/*
/ G_POP present, G_SUBPOP present
/----------------------------------------------------------------------------*/
%if %nrbquote(&g_pop) ne and %nrbquote(&g_subpop) ne %then
%do;
  %if %length(&g_poplbl) eq 0
      or
      %nrbquote(%upcase(&g_poplbl)) eq %nrbquote(%upcase(&l_popName))      /* ABR01 ABR02 */
      or
      %nrbquote(%upcase(&g_poplbl)) eq %nrbquote(%upcase(&l_popLabel))     /* ABR01 ABR02 */
      or
      %nrbquote(%upcase(&g_poplbl)) eq %nrbquote(%upcase(&l_popLabelNoPop))      /* ABR02 */
      %then
  %do;
    %put %str(RTW)ARNING: TU_HEADER: Population label is either missing or does not take account of subsetting condition.;
    %put %str(RTN)OTE: TU_HEADER: Population label will be re-assigned.;
    %let g_poplbl = %nrbquote(&l_pop &g_subpop);   /* ABR02 */
  %end;
%end; /* %if %nrbquote(&g_pop) ne and %nrbquote(&g_subpop) ne %then */
/*
/ G_POP missing, G_SUBPOP missing
/----------------------------------------------------------------------------*/
%if %nrbquote(&g_pop) eq and %nrbquote(&g_subpop) eq %then
%do;
  %if &g_poplbl eq %then
  %do;
    %put %str(RTN)OTE: TU_HEADER: Population label not specified, so default will be used.;
    %let g_poplbl = %sysfunc(putc(ALL SUBJECTS, $local.));
  %end;
%end; /* %if %nrbquote(&g_pop) eq and %nrbquote(&g_subpop) eq %then */
/*
/ Check that G_DSPLYTYP has a valid value, corresponding to either a figure,
/ a listing, or a table.
/ If &g_dsplytyp corresponds to a listing or figure, then check that
/ &cellindx is not "Y".                                                SL002
/ Allow additional valid values of C and P for g_dsplytyp.             SL003
/----------------------------------------------------------------------------*/
data _null_;
  if upcase("&g_dsplytyp") notin ("F" "L" "LI" "LO" "PP" "T" "TC" "C" "P") then
  do;
    put / "RTE" "RROR: TU_HEADER: Invalid value specified for display "
          "type (G_DSPLYTYP = &g_dsplytyp)."
        / ;
    call symput("g_abort", "1");
  end;
  if upcase("&g_dsplytyp") in ("F" "L" "LI" "LO" "PP" "P") and
    "&cellindx" eq "Y" then
  do;
    put / "RTE" "RROR: TU_HEADER: Listing or figure has been requested, "
          "so cell index should not be requested."
        / ;
    call symput("g_abort", "1");
  end;
run;
/*
/ Check that G_DSPLYNUM is not missing.
/----------------------------------------------------------------------------*/
%if %nrbquote(&g_dsplynum) eq %then
%do;
  %put %str(RTE)RROR: TU_HEADER: G_DSPLYNUM is missing.;
  %let g_abort = 1;                                                 /* SL002 */
%end;
/*
/ Call the tu_abort macro only if problems have been detected during
/ parameter validation. Note that tu_abort is called after all the parameter
/ validation checks have been executed, so that if more than one check fails,
/ then messages will be generated in the log for all the failed checks before
/ the program aborts.                                                  SL002
/----------------------------------------------------------------------------*/
%if &g_abort %then %do;
  %tu_abort()
%end;
/*
/ NORMAL PROCESSING
/----------------------------------------------------------------------------*/
/*
/ Declare global macro variable that will be created by this macro.
/----------------------------------------------------------------------------*/
%global g_header0;
/*
/ Generate SAS title 1 statement by: (i) calling %sysfunc with the putc
/ function to apply the $local format to the look-up key for "Protocol", (ii)
/ adding a colon, (iii) resolving G_STUDY_ID and G_STUDY_DESC. Left justify
/ the title by padding with blanks up to the line length.
/----------------------------------------------------------------------------*/
/*
/ Assign value to local macro variable to store the text for the title1
/ statement.
/ Note that the text is built in stages in order to remove the blanks spaces
/ that are generated by the putc function. Could also have achieved this with
/ %sysfunc and the trim function, however, this would have made the code less
/ easy to read.
/----------------------------------------------------------------------------*/
%let l_title1 = %sysfunc(putc(PROTOCOL, $local.));
%let l_title1 = &l_title1: %upcase(&g_study_id) &g_study_desc; /* YW001 */
/*
/ JHK001 
/ Based on G_DSPLYTYP left justify title1 using SAS/GRAPH options or
/ by padding the title with blanks.
/----------------------------------------------------------------------------*/
   %if %quote(&g_dsplytyp) eq F %then 
   %do;
      %let l_title1 = %qsysfunc(trim(&l_title1)); /* remove any trailing blanks */      
      title1 J=LEFT "&l_title1";
   %end;
   %else /* JHK001 Within this else do is the original justification code */
   %do;
      /*
      / Implement left justification for the first title by applying a format whose
      / length is equal to the line size.
      /----------------------------------------------------------------------------*/
      title1 "%sysfunc(putc(&l_title1, $&g_ls..))";
   %end;
/*
/ Generate SAS title2 statement by:
/
/ (i) calling %sysfunc with the putc function to apply the $local format to
/ the look-up key for "Population", (ii) adding a colon, (iii) resolving
/ G_POPLBL. Left justify the title by padding with blanks up to the line
/ length.
/
/ Note also that the word "population" (the local equivalent thereof) shall be
/ stripped from the decoded population variable label.
/
/ If G_DATADATE is not missing, (i) call %sysfunc with the putc function to
/ apply the $local format to the look-up key for "Data as of", (ii)
/ concatenate the resolved value of G_DATADATE. Place the resulting string
/ right-justified in the title.
/----------------------------------------------------------------------------*/
/*
/ Assign value to local macro variable to store the left hand text for the
/ title2 statement.
/ Note that the text is built in stages in order to remove the blanks spaces
/ that are generated by the putc function. Could also have achieved this with
/ %sysfunc and the trim function, however, this would have made the code less
/ easy to read.
/----------------------------------------------------------------------------*/
%let l_title2 = %sysfunc(putc(POPULATION, $local.));
/*
/ This code strips off the word "population" (or the localised equivalent of
/ this word).
/
/ SL003
/
/ In SAS version 8.2, the CALL RXCHANGE routine did not remove quoting from a
/ macro variable. However, in SAS version 9.1.3, any macro quoting that was 
/ previously applied to a macro variable is lost after the CALL RXCHANGE 
/ routine has been called. Therefore, apply macro quoting to G_POPLBL, after
/ CALL RXCHANGE, to ensure that special characters will not retain their
/ meaning when the value of G_POPLBL is used to construct L_TITLE2.
/
/ The %nrbquote function has previously been applied to G_POPLBL. If the
/ resolved value of G_POPLBL included ampersands that did not correspond to
/ macro variable references, then W-ARNING messages would already have been
/ written to the log. In order to avoid repeats of these messages, the %superq
/ function will be applied to G_POPLBL.
/----------------------------------------------------------------------------*/
%let rx = %sysfunc(rxparse(&l_title2 TO ));
%let times = 999;
%syscall rxchange(rx, times, g_poplbl);
%syscall rxfree(rx);
%let g_poplbl = %superq(g_poplbl);
%let l_title2 = &l_title2: &g_poplbl;
/*
/ JHK001 
/ Based on G_DSPLYTYP left justify title1 using SAS/GRAPH options or
/ by padding the title with blanks.
/----------------------------------------------------------------------------*/
   %if %quote(&g_dsplytyp) eq F %then 
   %do;
      %let l_title2 = %qsysfunc(trim(&l_title2)); /* remove any trailing blanks */
      %if %quote(&g_datadate) NE %then 
      %do;
         %let right_text = %sysfunc(putc(DATA AS OF, $local.));
         %let right_text = J=RIGHT "&right_text &g_datadate";
      %end;
      %else %let right_text = ;   
      title2 J=LEFT "&l_title2" &right_text;
   %end;
   %else /* JHK001 Within this else do is the original justification code */
   %do;
      /*
      / Implement left justification of second title, taking account of the cut-off
      / date in the title, if it has been specified by the user.
      /----------------------------------------------------------------------------*/
      title2
      %if %length(&g_datadate) eq 0 %then
      %do;
        "%sysfunc(putc(&l_title2, $&g_ls..))"
      %end;
      %else
      %do;
        /*
        / Note that the text is built in stages in order to remove the blanks spaces
        / that are generated by the putc function. Could also have achieved this
        / with %sysfunc and the trim function, however, this would have made the
        / code less easy to read.
        /--------------------------------------------------------------------------*/
        %let right_text = %sysfunc(putc(DATA AS OF, $local.));
        %let right_text = &right_text &g_datadate;
        %let num_spaces = %eval(&g_ls - (%length(&l_title2) + %length(&right_text)));
        "&l_title2%sysfunc(repeat(%str( ), &num_spaces - 1))&right_text"
      %end;
   %end;
/*
/ Semicolon is needed to end the title2 statement.
/----------------------------------------------------------------------------*/
;
/*
/ Generate SAS title3 statement by (i) calling %sysfunc with the putc
/ function to apply the $LOCAL format to the look-up key for either "Figure"
/ (if &g_dsplytyp is "F"), "Listing" (if &g_dsplytyp is "L", "LI", "LO", or
/ "PP"), "Table" (if &g_dsplytyp is "T" or "TC", and &cellindx is "N"), or
/ "Cell Index" (if &g_dsplytyp is "T" or "TC", and &cellindx is "Y"),
/ (ii) resolving &g_dsplynum. Allow the title to appear centred (do not pad
/ with blanks).                                                        SL002
/----------------------------------------------------------------------------*/
/*
/ The local macro variable FIG_LIST_TAB_CELL will be set to either "Figure",
/ "Listing", "Table", or "Cell index", depending upon the type of output that
/ is being generated.                                                  SL002
/ Allow for additional valid values of P and C for g_dsplytyp          SL003
/----------------------------------------------------------------------------*/
data _null_;
  length fig_list_tab_cell $ 200;
  if upcase("&g_dsplytyp") in ("L" "LI" "LO" "PP" "P") then
  do;
    fig_list_tab_cell = "%sysfunc(putc(LISTING, $local))";
  end;
  else if upcase("&g_dsplytyp") in ("T" "TC") then
  do;
    if "&cellindx" eq "N" then
      fig_list_tab_cell = "%sysfunc(putc(TABLE, $local))";
    else if "&cellindx" eq "Y" then
      fig_list_tab_cell = "%sysfunc(putc(CELL INDEX, $local))";
  end;
  else if upcase("&g_dsplytyp") in ("F") then
  do;
    fig_list_tab_cell = "%sysfunc(putc(FIGURE, $local))";
  end;
  else if upcase("&g_dsplytyp") in ("C") then
  do;
    fig_list_tab_cell = "%sysfunc(putc(CELL INDEX, $local))";
  end;

  call symput ("fig_list_tab_cell", trim(left(fig_list_tab_cell)));
run;
/*
/ Generate the title3 statement. Note that this title, and all the remaining
/ titles, needs to be centered, so there is no need to pad the text with
/ blank spaces.
/----------------------------------------------------------------------------*/
title3 "&fig_list_tab_cell &g_dsplynum";                      /* SL001 SL002 */
/*
/ ABR01 - Switch off the option for writing date to title3.
/----------------------------------------------------------------------------*/
options nodate;
/*
/ Generate title statements for the titles entered by the user via DDMM.
/ Note that the G_TITLE1 corresponds to the SAS title4 statement,
/ G_title2 corresponds to the SAS title5 statement etc.
/ Whilst the remaining title statements are being generated, the maximum
/ title number will also be noted, and stored in the global macro variable
/ G_HEADER0.
/----------------------------------------------------------------------------*/
%let g_header0 = 3;  /* ABR01 */
%let n = 4;
%do n = 4 %to 10;
  %let ddmm_title_num = %eval(&n - 3);
  %if %nrbquote(&&g_title&ddmm_title_num) ne %then %do;
    title&n "&&g_title&ddmm_title_num";
    %let g_header0 = &n;
  %end;
%end;
%MEND tu_header;
