/*--------------------------------------------------------------------------+
| Macro Name    : tu_pagenum.sas
|
| Macro Version : 2
|
| SAS version   : SAS v8.2
|
| Created By    : Shan Lee
|
| Date          : 22-May-2003
|
| Macro Purpose :
|
| The purpose of this macro is to implement page numbering (ie "page n of m")
| in a table, listing, or cell index. This macro assumes that there is a
| section of code within a data display macro, such as a Proc Report, that
| generates a table/listing/cell index minus the page numbering.
| %Tu_pagenum should be called before this section of code, with the
| "usage" parameter set to "before", and it should also be called after
| this section of code, with the "usage" parameter set to "after".
|
| When %tu_pagenum is called with "usage = before", all output generated
| by a proceeding Proc Report (or equivalent code) is directed to a
| temporary file; the file is assigned to the fileref specified by the REF
| parameter. When %tu_pagenum is called with "usage = after", the output
| from this temporary ASCII file is numbered and then written to a
| permanent ASCII file, whose name is derived by concatenating the value
| of the "outfile" parameter with an appropriate file extension (specified
| by the global macro variable G_TEXTFILESFX). After doing this, the
| temporary ASCII file is no longer needed, so %tu_pagenum deletes it.
|
| This macro is also used to delete the previous version of the listing or
| table at the start of a data display macro.
|
| Macro Design  : Procedure style
|
| Input Parameters :
|
| NAME           DESCRIPTION                              REQ/OPT   DEFAULT
|
| USAGE          Parameter to indicate whether            Req       None
|                %tu_pagenum is being called immediately
|                before or after the Proc Report or
|                equivalent code, or whether %tu_pagenum
|                is being used to delete the previous
|                version of listing/table.
|
| REF            Fileref to be assigned to the temporary  Req       None
|                ASCII file that is created by %tu_pagenum
|                when it is called with "USAGE = BEFORE".
|                Note that this parameter also needs to be
|                specified when "USAGE = AFTER", and should
|                have the same value as when the macro was
|                called with "USAGE = BEFORE".
|
| OUTFILE        Name and location of output file minus   Req       &g_outfile
|                extension.                               (if usage
|                                                         is delete
|                                                         or after)
|
| Output:
|
| When usage = before, tu_pagenum creates a temporary file for storing any
| output that will be generated by the proceding code (after the call to
| tu_pagenum). The fileref that the macro uses to allocate this temporary file
| is specified via the parameter "ref".
|
| When usage = after, tu_pagenum creates a permanent file, equivalent to the
| output stored in the temporary file, but in addition, page numbering is
| implemented in the permanent file. The location and name of this permanent
| file, minus the file extension, is specified via the parameter "outfile"
| (tu_pagenum adds a file extension so that SAFIRE will be able to convert the
| permanent ASCII file to a PDF file that meets IDSL requirements).
|
| Global macro variables created: None
|
|
| Macros called :
|  (@)tr_putlocals
|  (@)tu_putglobals
|  (@)tu_abort
|  (@)tu_chknames
|
|
| Example:
| %tu_pagenum(usage = delete, ref = temp)
|
|
| **************************************************************************
| Change Log :
|
| Modified By :             Shan Lee
| Date of Modification :    11-Jul-2003
| New Version Number :      1/2
| Modification ID :         SL001
| Reason For Modification : Amended after first round of testing.
|
| Modified By :             Shan Lee
| Date of Modification :    25-Sep-2003
| New Version Number :      1/3
| Modification ID :         SL002
| Reason For Modification : When USAGE = AFTER, ensure that there are control
|                           characters to indicate the start of each page,
|                           which can be recognised when paper copies of the
|                           output need to be printed.
|
| Modified By :             Shan Lee
| Date of Modification :    26-Sep-2003
| New Version Number :      1/4
| Modification ID :         SL003
| Reason For Modification : When USAGE = AFTER, set linesize and pagesize
|                           options in the file statement during the datastep
|                           that generates the permanent ASCII file. This is
|                           necessary because the required linesize and
|                           pagesize for the output is *not* the same as the
|                           linesize = and pagesize = system options, which
|                           have been assigned values that are appropriate
|                           for making the SAS log easier to read.
|
| Modified By :             Yongwei Wang
| Date of Modification :    26-Feb-2008
| New Version Number :      2/1
| Modification ID :         YW001
| Reason For Modification : 1. Modified 'call sysmtem("rm -f")' function to make
|                           it work for all platform, based on HRT0194
|                           2. Added more paremaeter validation on REF
|
+----------------------------------------------------------------------------*/


%MACRO tu_pagenum(
  usage = ,  /* Specify DELETE or BEFORE or AFTER */
  ref = ,  /* Fileref for temporary ASCII file */
  outfile = &g_outfile /* Location and name (minus extension) of output ASCII file */
      );


/*
/ Echo macro version number, and values of parameters and global macro
/ variables to the log.
/----------------------------------------------------------------------------*/

%local MacroVersion;
%let MacroVersion = 2;
%include "&g_refdata/tr_putlocals.sas";
%tu_putglobals(varsin = g_outfile g_textfilesfx g_ps g_ls g_refdata);


/*
/ Start of parameter validation.
/----------------------------------------------------------------------------*/


/*
/ Check that USAGE is set to either DELETE, BEFORE, or AFTER.
/----------------------------------------------------------------------------*/

%let usage = %upcase(%nrbquote(&usage));

%if &usage ne DELETE and &usage ne BEFORE and &usage ne AFTER %then
%do;

  data _null_;
    put // "RTE" "RROR: TU_PAGENUM: USAGE should be set to either DELETE, "
           "BEFORE, or AFTER."
        /  ;
    stop;
  run;

  %tu_abort(option = FORCE)

%end;


/*
/ The following parameter validation requirements:
/
/   If USAGE eq DELETE, then check that OUTFILE is not missing.
/
/   If USAGE eq BEFORE, then use %tu_chknames to check that REF is a non
/   missing SAS name.
/
/   If USAGE eq AFTER, then use %tu_chknames to check that REF is a
/   non-missing SAS name, and check that outfile is not missing.
/
/ ... will be achieved in the subsequent 2 stages.
/----------------------------------------------------------------------------*/


/*
/ If USAGE eq DELETE, or if USAGE eq AFTER, then check that OUTFILE is not
/ missing.
/----------------------------------------------------------------------------*/

%if (&usage eq DELETE or &usage eq AFTER) and %nrbquote(&outfile) eq %then
%do;

  data _null_;
    put // "RTE" "RROR: TU_PAGENUM: USAGE is set to either DELETE or AFTER, "
           "so OUTFILE should not be missing."
        /  ;
    stop;
  run;

  %tu_abort(option = FORCE)

%end;


/*
/ If USAGE eq BEFORE, or if USAGE eq AFTER, then use TU_CHKNAMES to check that
/ &ref is a non-missing SAS name.
/----------------------------------------------------------------------------*/

%if &usage eq BEFORE or &usage eq AFTER %then
%do;

  %if %nrbquote(&ref) eq %then
  %do;

    data _null_;
      put // "RTE" "RROR: TU_PAGENUM: USAGE is set to either BEFORE or AFTER, "
             "so REF should be a non-missing SAS name."
          /  ;
      stop;
    run;

    %tu_abort(option = FORCE)

  %end; /* %if %nrbquote(&ref) eq %then */
  %else
  %do;

    %if %tu_chknames(%nrbquote(&ref), DATA) ne %then
    %do;

      data _null_;
        put // "RTE" "RROR: TU_PAGENUM: USAGE is set to either BEFORE or AFTER,"
               " so REF should be a non-missing SAS name."
            /  ;
        stop;
      run;

      %tu_abort(option = FORCE)


    %end; /* %if %tu_chknames(%nrbquote(&ref), DATA) ne %then */

  %end; /* %else */

%end; /* %if &usage eq BEFORE or &usage eq AFTER %then */

/*
/ YW001: If USAGE eq AFTER, then check if REF exists and if it references
/ to an existing file.
/----------------------------------------------------------------------------*/

%if &usage eq AFTER %then
%do;
  
  data _null_;
    rc=fileref("&ref");
    if rc gt 0 then
    do;
       put // "RTE" "RROR: TU_PAGENUM: USAGE is set to AFTER,"
              " so REF(=&ref) should be an existing SAS file reference name."
           /  ;
       call symput('g_abort', '1');    
    end;
    else if rc lt 0 then
    do;
       put // "RTE" "RROR: TU_PAGENUM: USAGE is set to AFTER,"
              " so REF(=&ref) should point to an existing file."
           /  ;        
       call symput('g_abort', '1');    
    end;
    stop;
  run;

  %tu_abort()
  
%end; /* %if &usage eq AFTER */


/*
/ End of parameter validation.
/----------------------------------------------------------------------------*/


/*
/ Declare local macro variables that are created by this macro, and, if
/ necessary, assign initial values.
/----------------------------------------------------------------------------*/

%local catalog_entry num_pages;

%let catalog_entry = work.tu_pagenum.temp.output;


/*
/ If &usage = "delete", then delete the ASCII file specified by concatenating
/ &outfile with &g_textfilesfx.
/ YW001: Modified 'call system("rm -f") function to make it work for all
/ platforms.
/----------------------------------------------------------------------------*/

%if &usage eq DELETE %then
%do;

  filename _pagenu0 "&outfile...&g_textfilesfx";
  
  data _null_;
    rc=fdelete('_pagenu0');
  run;
  
  filename _pagenu0 clear;

%end; /* %if &usage eq DELETE %then */


/*
/ If &usage eq "before" , then
/
/   Assign the fileref whose name is given by &ref, to a temporary ASCII file,
/   created using the SAS catalogue access method.
/
/   Call Proc Printto to direct all proceedure output to the temporary ASCII
/   file.
/
/   Set the nonumber option, so that page numbers will not be shown in
/   procedure output.
/----------------------------------------------------------------------------*/

%if &usage eq BEFORE %then
%do;

  filename &ref catalog "&catalog_entry";

  proc printto print = &ref;
  run;

  options nonumber;

%end; /* %if &usage eq BEFORE %then */


/*
/ If &usage eq "after" , then
/
/   Call Proc Printto to re-direct all procedure output to the permanent
/   ASCII file whose name is derived by concatenating the value of &outfile
/   with &g_textfilesfx.
/
/   In a data _null_ step, read in each line of the temporary ASCII file,
/   counting the number of pages (= number of lines / pagesize) whilst doing
/   do.
/
/   Cancel any existing titles or footnote statements, so that titles and
/   and footnotes that were written to the temporary ASCII file will not also
/   be written to the permanent ASCII file in the subsequent data _null_
/   step. This is necessary because the data _null_ step uses FILE PRINT, so
/   existing title and footnote statements are recognised in addition to the
/   PUT statements within the datastep.
/
/   Read in the temporary ASCII file a second time: this time, output each
/   line to the permanent ASCII file, inserting "page n of m" in the first
/   line of each page. Note that the output location has already been
/   directed to the permanent ASCII file.
/
/   De-assign the fileref for the temporary ASCII file.
/
/   Re-direct the output location back to the default location.
/----------------------------------------------------------------------------*/

%if &usage eq AFTER %then
%do;

  proc printto print = "&outfile...&g_textfilesfx";                 /* SL002 */
  run;


  /*
  / In the following datastep, the number of pages will be counted.
  /--------------------------------------------------------------------------*/

  data _null_;

    infile &ref truncover end = eof;

    input;

    if eof then
    do;

      if mod(_n_, &g_ps) eq 0 then
      do;
        num_pages = _n_ / &g_ps;
      end;
      else
      do;
        temp = _n_ / &g_ps;
        num_pages = int(temp) + 1;
      end;

      call symput("num_pages", trim(left(num_pages)));

    end;

  run;


  /*
  / Cancel any existing title and footnote statements.
  /--------------------------------------------------------------------------*/

  title;                                                            /* SL002 */
  footnote;


  /*
  / In the following datastep, the permanent ASCII file will be generated,
  / which include the "page n of m"
  /--------------------------------------------------------------------------*/

  data _null_;

    infile &ref truncover length = reclen;
    file print ls = &g_ls ps = &g_ps;                         /* SL002 SL003 */

    length line page_text $&g_ls;

    input line $varying&g_ls.. reclen;

    retain page 0;

    if mod(_n_ - 1, &g_ps) eq 0 then
    do;
      page = page + 1;
      page_text = trim(left("%sysfunc(putc(PAGE, $local.)) "))
                  || " " || trim(left(page))
                  || " " || trim(left("%sysfunc(putc(OF, $local.))"))
                  || " &num_pages"
                  ;
      diff = &g_ls - length(page_text);
      line = substr(left(line), 1, diff) || trim(left(page_text));
    end;

    put line $&g_ls..;

  run;


  /*
  / The following statement DE-assigns the fileref.
  /--------------------------------------------------------------------------*/

  filename &ref;


  /*
  / Re-direct output back to the default location.
  /--------------------------------------------------------------------------*/

  proc printto print = print;                                       /* SL002 */
  run;


%end; /* %if &usage eq AFTER %then */


%MEND tu_pagenum;
