/*******************************************************************************
|
| Macro Name:      tu_perstd
|
| Macro Version:   4
|
| SAS Version:     8.2
|
| Created By:      Mark Luff / Eric Simms
|
| Date:            08-Jun-2004
|
| Macro Purpose:   For a specified input dataset, shall calculate the actual 
|                  day within a period given a specified date. If &EXPOSUREDSET 
|                  is given, the PERTSTDT will be added to the output data set 
|
| Macro Design:    Procedure Style
|
| Input Parameters:
|
| NAME              DESCRIPTION                             REQ/OPT  DEFAULT
| ----------------  --------------------------------------  -------  ----------
| DSETIN            Specifies the dataset for which the     REQ      (Blank)
|                   new variable containing the period day 
|                   is to be added.
|                   Valid values: a existing SAS data set 
|                   name
|
| DSETOUT           Specifies the name of the output        REQ      (Blank)
|                   dataset to be created.
|                   Valid values: valid dataset name
|
| EXPOSUREDSET      Specifies the EXPOSURE SI dataset. Will OPT      DMDATA.EXPOSURE
|                   be passed to %tu_pernum to derive 
|                   PERTSTDT.
|                   Valid values: Blank or a existing SAS                       
|                   data set name
|
| PERSTDTVAR        Specify name to use for the PERSTDT     OPT      perstdt
|                   variable which is generated by the
|                   tu_pernum macro. If blank, then this
|                   variable will not be created.
|
| PERTSTDTVAR       Specify name to use for the PERTSTDT    OPT      pertstdt
|                   variable which is generated by the
|                   tu_pernum macro. If blank, then this
|                   variable will not be created.
|
| REFDAT            Variable containing the date of         REQ      (Blank)
|                   interest.  Will be passed to 
|                   %tu_recalvisit to calculate related 
|                   VISITNUM
|                   Valid values:
|                   Name of a SAS variable that exists in 
|                   DSETIN
|
| RETTIM            Variable containing the time of         OPT      (Blank)
|                   interest.Will be passed to 
|                   %tu_recalvisit to calculated related 
|                   VISITNUM
|                   Valid values:
|                   Blank or Name of a SAS variable that 
|                   exists in DSETIN
|
|
| TMSLICEDSET       Specifies the TMSLICE SI dataset. Will  REQ      DMDATA.TMSLICEDSET
|                   be passed to %tu_pernum to derive 
|                   PERSTDT. 
|
| VARNAME           Name of the variable which will         REQ      (Blank)
|                   contain the actual day within period 
|                   of the REFDAT. 
|                   Valid values:
|                   Name of a SAS variable that exists in 
|                   DSETIN
|
| VARTNAME          Name of the variable which will contain OPT       tpersdy           
|                   the actual day within treatment period                            
|                   of the &REFDAT.                                                            
|                   Valid values: Blank or a valid SAS 
|                   variable name                    
|                                                                                       
| VARXNAME          Name of the variable which will contain OPT       xpersdy           
|                   the actual day within collection period                           
|                   of the &REFDAT.                                                            
|                   Valid values: Blank or a valid SAS 
|                   variable name            
|
| VISITDSET         Specifies the VISIT SI dataset. Will be REQ      DMDATA.VISIT
|                   passed to %tu_pernum to derive PERSTDT
| ----------------  --------------------------------------  -------  ----------
|
| The macro references the following datasets :-
| -----------------  -------  -------------------------------------------------
| Name               Req/Opt  Description
| -----------------  -------  -------------------------------------------------
| &DSETIN            Req      Parameter specified dataset
| DMDATA.EXPOSURE    Opt      SI dataset containing Exposure data
| DMDATA.TMSLICE     Req      SI dataset containing Time Slicing data
| DMDATA.VISIT       Req      SI dataset containing Visit Times data
| -----------------  -------  -------------------------------------------------
|
| Output:
|
| The macro outputs the following datasets :-
| -----------------  -------  -------------------------------------------------
| Name               Req/Opt  Description
| -----------------  -------  -------------------------------------------------
| &DSETOUT           Req      Parameter specified dataset
| -----------------  -------  -------------------------------------------------
|******************************************************************************
| Global macro variables created: NONE
|******************************************************************************
| Macros called:
|
|(@) tr_putlocals  
|(@) tu_abort       
|(@) tu_calctpernum
|(@) tu_chkvarsexist
|(@) tu_pernum      
|(@) tu_putglobals  
|(@) tu_recalcvisit 
|(@) tu_tidyup      
|(@) tu_timslc      
|******************************************************************************
| Example:
|    %tu_perstd(
|         dsetin  = _ae1,
|         dsetout = _ae2,
|         refdat  = aestdt,
|         reftim  = aesttm,
|         varname = aepersdy
|         );
|
|******************************************************************************
| Change Log
|
| Modified By:              Yongwei Wang
| Date of Modification:     23Feb2005
| New version/draft number: 1/2
| Modification ID:          YW001
| Reason For Modification:  1.Added a keep data set option to the output data set
|                             of %tu_pernum
|                           2.Set &dsetout to &dsetin when error is found.
|
| Modified By:              Yongwei Wang
| Date of Modification:     22Sep2005
| New version/draft number: 2/1
| Modification ID:          YW002
| Reason For Modification:  Requested by change request HRT0090
|                           1. Added two parameters &VARXNAME and &VARTNAME
|                           2. If any of &VARXNAME and &VARTNAME is not blank, check that
|                              &EXPOSUREDSET is not blank. 
|                           3. Added normal process to derive &VARXNAME and &VARTNAME
|
| Modified By:              Yongwei Wang
| Date of Modification:     14Feb2006
| New version/draft number: 3/1
| Modification ID:          YW003
| Reason For Modification:  Bug fix for last modification. PERSTDT is merged in twice 
|                           and the second one is removed. 
|
| Modified By:              Shan Lee
| Date of Modification:     31Oct2007
| New version/draft number: 4/1
| Modification ID:          SL001
| Reason For Modification:  Allow dataset options to be specified in dataset name 
|                           parameters - HRT0184.
|                           Introduce two new parameters, PERSTDTVAR and PERTSTDTVAR.
|                           Details of these parameters are given above, under 
|                           'Input Parameters'.
|
****************************************************************************************/

%macro tu_perstd (
   dsetin      = ,                /* Input dataset name */
   dsetout     = ,                /* Output dataset name */
   exposuredset= dmdata.exposure, /* Exposure dataset name */
   perstdtvar  = perstdt,         /* Variable name for period start date */
   pertstdtvar = pertstdt,        /* Variable name for date of start of treatment in period */
   refdat      = ,                /* Variable name for reference date */
   reftim      = ,                /* Variable name for reference time */
   tmslicedset = dmdata.tmslice,  /* Time slice dataset name */
   varname     = ,                /* Variable name for actual day within period */
   vartname    = tpersdy,         /* Variable name for actual day within treatment period  */
   varxname    = xpersdy,         /* Variable name for actual day within collection period */
   visitdset   = dmdata.visit     /* Visit dataset name */
   );

   /*
   / Echo parameter values and global macro variables to the log.
   /----------------------------------------------------------------------------*/
  
   %local MacroVersion;
   %let MacroVersion = 4 build 1;
   %include "&g_refdata/tr_putlocals.sas";
   %tu_putglobals() 

   /*
   / PARAMETER VALIDATION
   /----------------------------------------------------------------------------*/
   
   %local prefix i listvars loopi thisvar pertstdt;
   
   %let prefix = _perstd;   /* Root name for temporary work datasets */
   
   /*
   / Initialise counter for appending to temporary dataset names for the
   / purpose of tracking datasets through a number of optional sequential
   / data processing steps.
   /----------------------------------------------------------------------------*/
   
   %let i = 1;
   
   /*
   / Check for required parameters.
   /----------------------------------------------------------------------------*/
  
   %let listvars=DSETIN DSETOUT REFDAT VARNAME;
  
   %do loopi=1 %to 4;
      %let thisvar=%scan(&listvars, &loopi, %str( ));
      %let &thisvar=%nrbquote(&&&thisvar);
      
      %if &&&thisvar eq %then
      %do;
         %put %str(RTE)RROR: &sysmacroname: The parameter &thisvar is required.;
         %let g_abort=1;
      %end;    
   %end;  /* end of do-to loop */
   
   /*
   / Check that required dataset exists.
   / Allow dataset options to be specified - SL001.
   /----------------------------------------------------------------------------*/
   
   %if &dsetin ne %then
   %do; 
      %if %sysfunc(exist(%qscan(&dsetin, 1, %str(%()))) eq 0 %then
      %do;
         %put %str(RTE)RROR: &sysmacroname: The dataset DSETIN(=&dsetin) does not exist.;
         %let g_abort=1;
      %end;  
      %else %do;
         data &prefix._dsetinexist;
            if 0 then set %unquote(&dsetin);
         run;
      %end;
   %end; /* end-if on &dsetin ne */
   
   /*
   / Check that variable REFDAT, and &REFTIM if specified, exists on the input dataset.
   /----------------------------------------------------------------------------*/
   %if ( &dsetin ne ) and ( &refdat ne ) %then
   %do;
      %if %tu_chkvarsexist(&prefix._dsetinexist, &refdat &reftim) ne %then
      %do;
         %put %str(RTE)RROR: &sysmacroname: Data set DSETIN (=&dsetin) does not contain the variable REFDAT(=&refdat) or REFTIM(=&reftim.);

         %let g_abort=1;
      %end;  
   %end; /* end-if on ( &dsetin ne ) and ( &refdat ne ) */
   
   /*
   / Check that new variable to be created does not already exist on the input
   / dataset.
   /----------------------------------------------------------------------------*/
    
   %if ( &dsetin ne ) and ( &varname ne ) %then
   %do;  
      %if %tu_chkvarsexist(&prefix._dsetinexist, &varname) eq %then 
      %do;
         %put %str(RTE)RROR: &sysmacroname: Data set DSETIN (=&dsetin) already has a variable named VARNAME(=&varname).;
         %let g_abort=1;
      %end;  
   %end; /* end-if on ( &dsetin ne ) and ( &varname ne ) */ 
   
   /* YW002: Check if &EXPOSUREDSET is blank, if &VARXNAME or &VARTNAME is not blank */
   /* SL001: Check also that &PERTSTDTVAR is blank */
   %if %nrbquote(&exposuredset) eq %then
   %do;
      %if %nrbquote(&varxname) ne %then 
      %do;
         %put %str(RTE)RROR: &sysmacroname: Because VARXNAME(=&varxname) is not blank, EXPOSUREDSET should not be blank.;
         %let g_abort=1;      
      %end;
      %if %nrbquote(&vartname) ne %then 
      %do;
         %put %str(RTE)RROR: &sysmacroname: Because VARTNAME(=&vartname) is not blank, EXPOSUREDSET should not be blank.;
         %let g_abort=1;         
      %end;      
      %if %nrbquote(&pertstdtvar) ne %then 
      %do;
         %put %str(RTE)RROR: &sysmacroname: EXPOSUREDSET is blank, so cannot create variable specified via PERTSTDTVAR(=&pertstdtvar).;
         %let g_abort=1;         
      %end;
   %end;
         
   /*
   / Check that names to use for the PERSTDT and PERTSTDT variables, created by
   / tu_pernum, are valid SAS variable names. SL001
   /----------------------------------------------------------------------------*/

   %if %length(&perstdtvar&pertstdtvar) ne 0 %then
   %do;
     %if %length(%tu_chknames(&perstdtvar &pertstdtvar, VARIABLE)) ne 0 %then
     %do;
       %put %str(RTE)RROR: &sysmacroname: parameters PERSTDTVAR(=&perstdtvar) and PERTSTDTVAR(=&pertstdtvar) should be either blank or valid SAS variable names.;
       %let g_abort=1;         
     %end;        
   %end;

   %if &g_abort eq 1 %then
   %do;
      %tu_abort;
   %end;

   /*
   / NORMAL PROCESSING
   /----------------------------------------------------------------------------*/
   
   /*
   / If &exposuredset is not blank, PERTSTDT is required.
   /----------------------------------------------------------------------------*/
   
   %if %nrbquote(&exposuredset) ne %then %let pertstdt=pertstdt;
   %else %let pertstdt=;
   
   /*
   / If the input dataset name is the same as the output dataset name,
   / write a note to the log.
   / Ignore dataset options when comparing dataset names - SL001.
   /----------------------------------------------------------------------------*/
   
   %if %qscan(%upcase(&dsetin), 1, %str(%()) eq %qscan(%upcase(&dsetout), 1, %str(%()) %then
   %do;
      %put %str(RTN)OTE: &sysmacroname: The input dataset name (&dsetin) is the same as the output dataset name (&dsetout).;
   %end;  /* end-if Specified datasets for DSETIN and DSETOUT have same names.  */ 
   
   /*
   / Create a data set contains only STUDYID SUBJID &REFDAT &REFTIM from &DSETIN
   /----------------------------------------------------------------------------*/
   
   proc sort data=%unquote(&dsetin) out=&prefix._ds&i (keep=studyid subjid &refdat &reftim) nodupkey;
      by studyid subjid &refdat &reftim;
   run;          
   
   /*
   / Call %tu_recalcvisit and %tu_timslc to add period to the data set.
   /----------------------------------------------------------------------------*/
      
   %tu_recalcvisit (
      dsetin  = &prefix._ds&i,
      dsetout = &prefix._ds%eval(&i+1),
      refdat  = &refdat,
      reftim  = &reftim 
      );
  
   %let i = %eval(&i + 1);
   
   %tu_timslc (
      dsetin      = &prefix._ds&i,
      dsetout     = &prefix._ds%eval(&i+1),
      tmslicedset = &tmslicedset
      );
  
   %let i = %eval(&i + 1);
   
   /*
   / If PERIOD was not added by step above, write an error message to the log
   /----------------------------------------------------------------------------*/
   
   %if %tu_chkvarsexist(&prefix._ds&i, PERNUM) ne %then %do;   
      %put %str(RTW)ARNING: &sysmacroname: VARNAME(=&varname) can not be added because PERNUM was not added by %nrstr(%tu_timslc).;
      data %unquote(&dsetout);
         set %unquote(&dsetin);
      run;
      %goto endmac;   
   %end;
  
   /*
   / Call %tu_pernum to create period data set to get period start date and time.
   /----------------------------------------------------------------------------*/
   
   %tu_pernum (
      dsetout       = &prefix._dspernum,
      exposuredset  = &exposuredset,
      tmslicedset   = &tmslicedset,
      visitdset     = &visitdset
      );
       
   /*
   / If PERIOD data was not created, write an error message to the log
   /----------------------------------------------------------------------------*/
                
   %if %sysfunc(exist(&prefix._dspernum)) eq 0 %then 
   %do;   
      %put %str(RTW)ARNING: &sysmacroname: VARNAME(=&varname) can not be added because period information was not added by %nrstr(%TU_PERNUM).;      
      data %unquote(&dsetout);
         set %unquote(&dsetin);
      run;
      %goto endmac;  
   %end;
         
   /*
   / Merge two data sets created above by STUDYID, SUBJID and PERNUM
   /----------------------------------------------------------------------------*/  
   
   proc sort data=&prefix._dspernum nodupkey
             out=&prefix._dspernum2(keep=studyid subjid pernum perstdt &pertstdt);
      by studyid subjid pernum perstdt;
      where pernum gt .;
   run;
   
   proc sort data=&prefix._ds&i out=&prefix._ds%eval(&i+1) (keep=studyid subjid pernum &refdat &reftim);  /* YW001 */
      by studyid subjid pernum;
   run;
   
   %let i = %eval(&i + 1);
   
   data &prefix._ds%eval(&i+1); 
      merge &prefix._ds&i (in=__in__)
            &prefix._dspernum2;            
      by studyid subjid pernum;
      drop pernum;
            
      if __in__;      
   run;
   
   %let i = %eval(&i + 1);
   
   /*
   / YW002: If &VARTNAME is not blank, call %tu_calctpernum to calculate TPERNUM;
   / rename PERNUM to TPERNUM in period data set. merge input data set with PERIOD 
   / data set by STUDYID, SUBJID and TPERNUM to get PERTSTDT; and rename PERTSTDT 
   / to TPERTSTDT
   /----------------------------------------------------------------------------*/ 
     
   %if %nrbquote(&vartname) ne %then
   %do;
   
      %tu_calctpernum (
         dsetin      = &prefix._ds&i,                
         dsetout     = &prefix._ds%eval(&i+1),                
         exposuredset= &exposuredset, 
         refdat      = &refdat,                
         reftim      = &reftim,                
         tmslicedset = &tmslicedset,  
         visitdset   = &visitdset    
         );
      
      %let i = %eval(&i + 1); 
        
      proc sort data=&prefix._ds&i out=&prefix._ds%eval(&i+1);  
         by studyid subjid tpernum;
      run;
      
      %let i = %eval(&i + 1);
     
      data &prefix._ds%eval(&i+1); 
         merge &prefix._ds&i (in=__in__)
               &prefix._dspernum2 (rename=(pernum=tpernum &pertstdt=tpertstdt) drop=perstdt); /* YW003: added drop */           
         by studyid subjid tpernum;
         keep studyid subjid perstdt &pertstdt tpertstdt &refdat &reftim;
               
         if __in__;      
      run;
      
      %let i = %eval(&i + 1);
 
   %end; /* %nrbquote(&vartname) ne */
   
   /*
   /  Merge &DSETIN with the data set created above by STUDYID SUBJID &REFDAT and 
   /  &REFTIM. Calculate &VARNANME
   /----------------------------------------------------------------------------*/
   
   proc sort data=&prefix._ds&i out=&prefix._ds%eval(&i+1) nodupkey;
      by studyid subjid &refdat &reftim;
   run;
   
   %let i = %eval(&i + 1);
   
   proc sort data=%unquote(&dsetin) out=&prefix._dsin;
      by studyid subjid &refdat &reftim;
   run;
      
   data %unquote(&dsetout);
      merge &prefix._dsin (in=__in__)
            &prefix._ds&i;
      by studyid subjid &refdat &reftim;

      /*
      / SL001
      /
      / The variables PERSTDT and PERTSTDT were created by tu_pernum. (PERTSTDT
      / will only have been created if EXPOSUREDSET is not blank.)
      / These variables will either be dropped or renamed, depending on what the
      / the user has specified via the parameters PERSTDTVAR and PERTSTDTVAR.
      /-------------------------------------------------------------------------*/

      %if %length(&perstdtvar) eq 0 %then
      %do;
        drop perstdt;
      %end;
      %else
      %do;
        rename perstdt = &perstdtvar;
      %end;

      %if %length(&exposuredset) ne 0 %then
      %do;
        %if %length(&pertstdtvar) eq 0 %then
        %do;
          drop pertstdt;
        %end;
        %else
        %do;
          rename pertstdt = &pertstdtvar;
        %end;
      %end;
      
      if __in__;
      
      if ( &refdat ne . ) and ( perstdt ne . ) then &varname=&refdat - perstdt + 1;
      
      /*   
      / YW002: If &varxname is not blank, calculate &VARXNAME
      /-------------------------------------------------------------------------*/
     
      %if %nrbquote(&varxname) ne %then
      %do;
         if ( not missing(&refdat)) and ( not missing(pertstdt) ) then
         do;
            if &refdat ge pertstdt then &varxname = &refdat - pertstdt + 1;
            else &varxname = &refdat - pertstdt;
         end;
      %end; /* %nrbquote(&varxname) ne */
      
      /*   
      / YW002: If &vartname is not blank, calculate &VARTNAME
      /-------------------------------------------------------------------------*/
      
      %if %nrbquote(&vartname) ne %then
      %do;       
         if ( not missing(&refdat)) and ( not missing(tpertstdt) ) then
         do;
            if &refdat ge tpertstdt then &vartname = &refdat - tpertstdt + 1;
            else &vartname = &refdat - tpertstdt;
         end;
         
         drop tpertstdt;
         
      %end; /* %nrbquote(&vartname) ne */     
      
   run;   
   
%ENDMAC: 

   /*
   / Delete temporary datasets used in this macro.      
   /----------------------------------------------------------------------------*/
   %tu_tidyup(
      rmdset=&prefix:, 
      glbmac=NONE
      );

%mend tu_perstd;


