# R Script Generator — pure R, no Shiny

fct_codegen <- function(pop, grouping, stats, fmt) {
  tv <- grouping$trt_var
  fv <- pop$flag_var; fval <- pop$flag_val
  inc_total <- grouping$include_total
  vars <- grouping$analysis_vars
  tc <- fmt$titles; col <- fmt$cols; pg <- fmt$page

  title_str <- paste(tc$titles, collapse = " \u2014 ")
  f <- paste0("%.", stats$cont_dec, "f")
  f1 <- paste0("%.", stats$cont_dec + 1, "f")
  pf <- paste0("%.", stats$pct_dec, "f")

  L <- c(
    "# ============================================================================",
    sprintf("# %s", title_str),
    sprintf("# Population: %s", tc$population),
    sprintf("# Generated by arbuilder on %s", Sys.Date()),
    "# ============================================================================", "",
    "library(arframe)", "library(dplyr)", "library(tidyr)", "library(readr)", "",
    "# --- Load & filter ---",
    'adsl <- read_csv("data/adsl.csv") |>',
    sprintf('  filter(%s == "%s")', fv, fval), "")

  # Big N
  if (inc_total) {
    L <- c(L, sprintf('big_n <- adsl |> count(%s, name = "N") |>', tv),
      sprintf('  bind_rows(tibble(%s = "Total", N = nrow(adsl)))', tv), "")
  } else {
    L <- c(L, sprintf('big_n <- adsl |> count(%s, name = "N")', tv), "")
  }

  # Variable blocks
  for (v in vars) {
    vn <- v$variable; vl <- v$label; sn <- tolower(vn)
    if (v$type == "continuous") {
      L <- c(L, sprintf("# --- %s ---", vl), sprintf("%s_stats <- adsl |>", sn))
      if (inc_total) L <- c(L, sprintf('  bind_rows(adsl |> mutate(%s = "Total")) |>', tv))
      se <- character(0)
      if ("n" %in% stats$cont_stats) se <- c(se, '    N = as.character(n())')
      if ("mean_sd" %in% stats$cont_stats) se <- c(se,
        sprintf('    `Mean (SD)` = sprintf("%s (%s)", mean(%s, na.rm = TRUE), sd(%s, na.rm = TRUE))', f, f1, vn, vn))
      if ("median" %in% stats$cont_stats) se <- c(se,
        sprintf('    Median = sprintf("%s", median(%s, na.rm = TRUE))', f, vn))
      if ("q1_q3" %in% stats$cont_stats) se <- c(se,
        sprintf('    `Q1, Q3` = sprintf("%s, %s", quantile(%s, .25, na.rm = TRUE), quantile(%s, .75, na.rm = TRUE))', f, f, vn, vn))
      if ("min_max" %in% stats$cont_stats) se <- c(se,
        sprintf('    `Min, Max` = sprintf("%s, %s", min(%s, na.rm = TRUE), max(%s, na.rm = TRUE))', f, f, vn, vn))
      L <- c(L, sprintf("  group_by(%s) |>", tv), "  summarise(",
        paste(se, collapse = ",\n"), "  ) |>",
        sprintf("  pivot_longer(-%s, names_to = \"stat\") |>", tv),
        sprintf("  pivot_wider(names_from = %s) |>", tv),
        sprintf('  mutate(stat = c("%s", paste0("  ", stat[-1])))', vl), "")
    } else {
      L <- c(L, sprintf("# --- %s ---", vl), sprintf("%s_stats <- adsl |>", sn))
      if (inc_total) L <- c(L, sprintf('  bind_rows(adsl |> mutate(%s = "Total")) |>', tv))
      val_expr <- switch(stats$cat_fmt,
        npct   = sprintf('sprintf("%%d (%s%%%%)", n, n / N * 100)', pf),
        n_only = 'sprintf("%d", n)',
        nn_pct = sprintf('sprintf("%%d/%%d (%s%%%%)", n, N, n / N * 100)', pf))
      L <- c(L, sprintf("  count(%s, %s) |>", tv, vn),
        sprintf('  left_join(big_n, by = "%s") |>', tv),
        sprintf("  mutate(value = %s) |>", val_expr),
        sprintf("  select(%s, stat = %s, value) |>", tv, vn),
        sprintf("  pivot_wider(names_from = %s) |>", tv),
        sprintf('  mutate(stat = c("%s", paste0("  ", stat[-1])))', vl), "")
    }
  }

  # Stack
  var_names <- paste0(tolower(purrr::map_chr(vars, "variable")), "_stats")
  L <- c(L, sprintf("tbl_demog <- bind_rows(%s)", paste(var_names, collapse = ", ")), "")

  # arframe pipeline
  tl <- paste(sprintf('  "%s"', tc$titles), collapse = ",\n")
  fn_line <- if (length(tc$footnotes) > 0) {
    sprintf("  fr_footnotes(%s) |>", paste(sprintf('"%s"', tc$footnotes), collapse = ", "))
  }
  L <- c(L, "tbl_demog |>", "  fr_table() |>", "  fr_titles(", tl, ",",
    sprintf('    population = "%s"', tc$population), "  ) |>",
    fn_line,
    "  fr_cols(",
    sprintf('    param = fr_col(label = "Parameter", width = %s, align = "left"),', col$stub_width),
    sprintf('    .align = "%s"', col$body_align), "  ) |>",
    sprintf('  fr_header(bold = TRUE, align = "center") |>'),
    sprintf('  fr_hlines("%s") |>', pg$hline_preset),
    sprintf('  fr_page(orientation = "%s", paper = "%s", font_size = %d, font_family = "%s") |>',
      pg$orientation, pg$paper, pg$font_size, pg$font_family),
    '  fr_render("output.rtf")')

  paste(L, collapse = "\n")
}
