# Template-aware code generation dispatch
# Shared header/data/format sections + template-specific ARD section

fct_codegen_dispatch <- function(template, data_cfg, grouping, var_configs, format_cfg,
                                  combined_groups = NULL) {
  output_type <- fct_template_output_type(template)

  sections <- c(
    fct_codegen_header_dispatch(template, output_type),
    fct_codegen_data_dispatch(template, data_cfg),
    fct_codegen_ard_dispatch(template, grouping, var_configs),
    if (output_type == "table") fct_codegen_format(format_cfg) else "",
    if (output_type == "table") fct_codegen_render(format_cfg) else "",
    if (output_type == "figure") fct_codegen_figure_render(template, format_cfg) else "",
    if (output_type == "listing") fct_codegen_listing_render(format_cfg) else ""
  )
  paste(sections[nzchar(sections)], collapse = "\n")
}

fct_codegen_header_dispatch <- function(template, output_type) {
  libs <- c("dplyr", "tidyr", "arframe")
  if (output_type == "figure") libs <- c(libs, "ggplot2")
  if (template == "km_plot") libs <- c(libs, "survival", "patchwork")
  if (template %in% c("tte", "forest")) libs <- c(libs, "survival", "broom")

  paste0(
    "# =============================================================================\n",
    "# Generated by arbuilder\n",
    "# Template: ", template, "\n",
    "# Date: ", Sys.Date(), "\n",
    "# =============================================================================\n",
    "\n",
    paste0("library(", libs, ")", collapse = "\n"),
    "\n\n"
  )
}

fct_codegen_data_dispatch <- function(template, data_cfg) {
  required <- fct_template_required_datasets(template)
  pop_flag <- data_cfg$pop_flag

  lines <- "# --- Data ---"
  for (ds in required) {
    path <- data_cfg$paths[[ds]] %||% paste0("data/", ds, ".rds")
    lines <- c(lines, paste0(ds, ' <- readRDS("', path, '")'))
  }

  # Apply pop filter to ADSL
  if (!is.null(pop_flag) && nzchar(pop_flag)) {
    lines <- c(lines, paste0('adsl <- adsl |> filter(', pop_flag, ' == "Y")'))
  }

  paste(c(lines, ""), collapse = "\n")
}

fct_codegen_ard_dispatch <- function(template, grouping, var_configs) {
  trt_var <- grouping$trt_var

  switch(template,
    # Demographics — use existing codegen
    demog = fct_codegen_ard(grouping, var_configs),

    # Disposition
    disposition = fct_codegen_ard_disposition(grouping, var_configs),

    # Populations
    populations = fct_codegen_ard_populations(grouping),

    # Hierarchical tables (MH, CM)
    medical_history =, prior_meds =, concomitant_meds =
      fct_codegen_ard_hierarchical(template, grouping, var_configs),

    # AE tables
    ae_summary = fct_codegen_ard_ae_summary(grouping),
    ae_socpt =, ae_related =, ae_grade34 =, ae_serious =,
    ae_fatal =, ae_dose_reduced =, ae_drug_interrupted =,
    ae_drug_withdrawn =, ae_frequency =
      fct_codegen_ard_ae_socpt(template, grouping),
    ae_by_severity = fct_codegen_ard_ae_severity(grouping),

    # Exposure
    exposure = fct_codegen_ard_exposure(grouping, var_configs),

    # TTE
    tte = fct_codegen_ard_tte(grouping, var_configs),

    # Response
    response = fct_codegen_ard_response(grouping, var_configs),

    # Continuous efficacy
    efficacy_cont = fct_codegen_ard_efficacy_cont(grouping, var_configs),

    # BDS (lab/vitals/ecg)
    lab_results =, vitals =, ecg = fct_codegen_ard_bds(grouping, var_configs),

    # Shift
    lab_shift =, vitals_shift =, ecg_shift = fct_codegen_ard_shift(grouping, var_configs),

    # Marked abnormalities
    marked_abnorm = fct_codegen_ard_marked(grouping, var_configs),

    # Figures
    km_plot = fct_codegen_fig_km(grouping, var_configs),
    waterfall = fct_codegen_fig_waterfall(grouping, var_configs),
    forest = fct_codegen_fig_forest(grouping, var_configs),
    swimmer = fct_codegen_fig_swimmer(grouping, var_configs),

    # Listings
    listing_demographics =, listing_ae =, listing_lab =,
    listing_discontinued =, listing_custom =
      fct_codegen_listing(template, var_configs),

    # Fallback
    paste("# --- ARD Construction ---\n# Template:", template, "(codegen not yet implemented)\n")
  )
}

# ── Template-specific codegen functions ──

fct_codegen_ard_disposition <- function(grouping, var_configs) {
  trt <- grouping$trt_var
  paste(c(
    "# --- ARD: Disposition ---",
    "",
    paste0("big_n <- adsl |> count(", trt, ', name = "N")'),
    "",
    "# Completion status",
    paste0("ard_completion <- adsl |>"),
    paste0("  count(", trt, ", EOSSTT) |>"),
    paste0("  group_by(", trt, ") |>"),
    "  mutate(pct = n / sum(n) * 100) |>",
    "  ungroup()",
    "",
    "# Discontinuation reasons",
    paste0("ard_disc_reason <- adsl |>"),
    paste0('  filter(EOSSTT == "DISCONTINUED") |>'),
    paste0("  count(", trt, ", DCREASCD) |>"),
    paste0("  group_by(", trt, ") |>"),
    "  mutate(pct = n / sum(n) * 100) |>",
    "  ungroup()",
    ""
  ), collapse = "\n")
}

fct_codegen_ard_populations <- function(grouping) {
  trt <- grouping$trt_var
  flags <- grouping$analysis_vars
  if (length(flags) == 0) flags <- c("SAFFL", "ITTFL", "EFFFL")

  lines <- c("# --- ARD: Analysis Populations ---", "")
  for (fl in flags) {
    lines <- c(lines,
      paste0("ard_", tolower(fl), " <- adsl |>"),
      paste0("  group_by(", trt, ") |>"),
      paste0('  summarise(n = sum(', fl, ' == "Y", na.rm = TRUE), .groups = "drop") |>'),
      paste0("  mutate(N = n(), pct = n / N * 100)"),
      ""
    )
  }
  paste(lines, collapse = "\n")
}

fct_codegen_ard_hierarchical <- function(template, grouping, var_configs) {
  trt <- grouping$trt_var
  ds <- switch(template, medical_history = "adcm", prior_meds = "adcm", concomitant_meds = "adcm", "adcm")
  parent <- var_configs$.parent_var %||% "CMCLAS"
  child <- var_configs$.child_var %||% "CMDECOD"

  paste(c(
    paste0("# --- ARD: Hierarchical (", template, ") ---"),
    "",
    paste0("# Merge treatment from ADSL"),
    paste0("analysis <- ", ds, " |>"),
    paste0('  inner_join(adsl |> select(USUBJID, ', trt, '), by = "USUBJID")'),
    "",
    paste0("big_n <- adsl |> count(", trt, ', name = "N")'),
    "",
    "# Parent-level counts (subjects with any event in category)",
    paste0("ard_parent <- analysis |>"),
    paste0("  distinct(USUBJID, ", trt, ", ", parent, ") |>"),
    paste0("  count(", trt, ", ", parent, ") |>"),
    paste0("  group_by(", trt, ") |>"),
    "  ungroup()",
    "",
    "# Child-level counts",
    paste0("ard_child <- analysis |>"),
    paste0("  distinct(USUBJID, ", trt, ", ", parent, ", ", child, ") |>"),
    paste0("  count(", trt, ", ", parent, ", ", child, ") |>"),
    paste0("  group_by(", trt, ") |>"),
    "  ungroup()",
    ""
  ), collapse = "\n")
}

fct_codegen_ard_ae_summary <- function(grouping) {
  trt <- grouping$trt_var
  paste(c(
    "# --- ARD: AE Summary ---",
    "",
    paste0("big_n <- adsl |> count(", trt, ', name = "N")'),
    "",
    "# Subjects with any TEAE",
    paste0("ard_any <- adae |>"),
    paste0("  distinct(USUBJID, ", trt, ") |>"),
    paste0("  count(", trt, ", name = \"n\")"),
    "",
    "# Subjects with any serious AE",
    paste0("ard_serious <- adae |>"),
    paste0('  filter(AESER == "Y") |>'),
    paste0("  distinct(USUBJID, ", trt, ") |>"),
    paste0("  count(", trt, ", name = \"n\")"),
    "",
    "# Subjects with any related AE",
    paste0("ard_related <- adae |>"),
    paste0('  filter(AEREL %in% c("RELATED", "PROBABLE", "POSSIBLE", "Y")) |>'),
    paste0("  distinct(USUBJID, ", trt, ") |>"),
    paste0("  count(", trt, ", name = \"n\")"),
    "",
    "# Subjects with AE leading to discontinuation",
    paste0("ard_disc <- adae |>"),
    paste0('  filter(AEACN == "DRUG WITHDRAWN") |>'),
    paste0("  distinct(USUBJID, ", trt, ") |>"),
    paste0("  count(", trt, ", name = \"n\")"),
    "",
    "# Deaths",
    paste0("ard_death <- adae |>"),
    paste0('  filter(AEOUT == "FATAL" | AESDTH == "Y") |>'),
    paste0("  distinct(USUBJID, ", trt, ") |>"),
    paste0("  count(", trt, ", name = \"n\")"),
    ""
  ), collapse = "\n")
}

fct_codegen_ard_ae_socpt <- function(template, grouping) {
  trt <- grouping$trt_var
  filter_line <- switch(template,
    ae_socpt = "",
    ae_related = '  filter(AEREL %in% c("RELATED", "PROBABLE", "POSSIBLE", "Y")) |>',
    ae_grade34 = '  filter(AETOXGR %in% c("3", "4", "5")) |>',
    ae_serious = '  filter(AESER == "Y") |>',
    ae_fatal = '  filter(AEOUT == "FATAL" | AESDTH == "Y") |>',
    ae_dose_reduced = '  filter(AEACN == "DOSE REDUCED") |>',
    ae_drug_interrupted = '  filter(AEACN == "DRUG INTERRUPTED") |>',
    ae_drug_withdrawn = '  filter(AEACN == "DRUG WITHDRAWN") |>',
    ae_frequency = "",
    ""
  )

  lines <- c(
    paste0("# --- ARD: AE SOC/PT (", template, ") ---"),
    "",
    paste0("big_n <- adsl |> count(", trt, ', name = "N")'),
    ""
  )

  if (nzchar(filter_line)) {
    lines <- c(lines, "adae_filtered <- adae |>", filter_line, "  identity()", "")
  } else {
    lines <- c(lines, "adae_filtered <- adae", "")
  }

  lines <- c(lines,
    "# Any TEAE row",
    paste0("ard_any <- adae_filtered |>"),
    paste0("  distinct(USUBJID, ", trt, ") |>"),
    paste0("  count(", trt, ", name = \"n\")"),
    "",
    "# SOC-level counts",
    paste0("ard_soc <- adae_filtered |>"),
    paste0("  distinct(USUBJID, ", trt, ", AEBODSYS) |>"),
    paste0("  count(", trt, ", AEBODSYS)"),
    "",
    "# PT-level counts",
    paste0("ard_pt <- adae_filtered |>"),
    paste0("  distinct(USUBJID, ", trt, ", AEBODSYS, AEDECOD) |>"),
    paste0("  count(", trt, ", AEBODSYS, AEDECOD)"),
    ""
  )

  if (template == "ae_frequency") {
    lines <- c(lines,
      "# Sort SOC and PT by descending frequency",
      "soc_order <- ard_soc |> group_by(AEBODSYS) |> summarise(total = sum(n)) |> arrange(desc(total))",
      "pt_order <- ard_pt |> group_by(AEBODSYS, AEDECOD) |> summarise(total = sum(n)) |> arrange(desc(total))",
      ""
    )
  }

  paste(lines, collapse = "\n")
}

fct_codegen_ard_ae_severity <- function(grouping) {
  trt <- grouping$trt_var
  paste(c(
    "# --- ARD: AE by Severity ---",
    "",
    paste0("big_n <- adsl |> count(", trt, ', name = "N")'),
    "",
    "# Max severity per subject per SOC/PT",
    paste0("ard_severity <- adae |>"),
    paste0("  group_by(USUBJID, ", trt, ", AEBODSYS, AEDECOD) |>"),
    "  summarise(max_sev = max(AETOXGR, na.rm = TRUE), .groups = \"drop\") |>",
    paste0("  count(", trt, ", AEBODSYS, AEDECOD, max_sev)"),
    ""
  ), collapse = "\n")
}

fct_codegen_ard_exposure <- function(grouping, var_configs) {
  trt <- grouping$trt_var
  paste(c(
    "# --- ARD: Exposure ---",
    "",
    paste0("ard_exposure <- adex |>"),
    paste0("  group_by(", trt, ") |>"),
    "  summarise(",
    "    n = n(),",
    "    mean_dur = mean(AVAL, na.rm = TRUE),",
    "    sd_dur = sd(AVAL, na.rm = TRUE),",
    "    median_dur = median(AVAL, na.rm = TRUE),",
    "    min_dur = min(AVAL, na.rm = TRUE),",
    "    max_dur = max(AVAL, na.rm = TRUE),",
    '    .groups = "drop"',
    "  )",
    ""
  ), collapse = "\n")
}

fct_codegen_ard_tte <- function(grouping, var_configs) {
  trt <- grouping$trt_var
  paramcd <- var_configs$paramcd %||% "PFS"
  paste(c(
    "# --- ARD: Time-to-Event ---",
    "",
    paste0('tte_data <- adtte |> filter(PARAMCD == "', paramcd, '")'),
    "",
    "# KM estimates",
    paste0("km_fit <- survfit(Surv(AVAL, 1 - CNSR) ~ ", trt, ", data = tte_data)"),
    "km_summary <- summary(km_fit)",
    "",
    "# Log-rank test",
    paste0("lr_test <- survdiff(Surv(AVAL, 1 - CNSR) ~ ", trt, ", data = tte_data)"),
    "lr_pval <- 1 - pchisq(lr_test$chisq, df = length(lr_test$n) - 1)",
    "",
    "# Cox PH for hazard ratio",
    paste0("cox_fit <- coxph(Surv(AVAL, 1 - CNSR) ~ ", trt, ", data = tte_data)"),
    "cox_tidy <- tidy(cox_fit, conf.int = TRUE, exponentiate = TRUE)",
    ""
  ), collapse = "\n")
}

fct_codegen_ard_response <- function(grouping, var_configs) {
  trt <- grouping$trt_var
  paste(c(
    "# --- ARD: Response ---",
    "",
    paste0("big_n <- adsl |> count(", trt, ', name = "N")'),
    "",
    "# BOR distribution",
    paste0("ard_bor <- adrs |>"),
    paste0('  filter(PARAMCD == "BOR") |>'),
    paste0("  count(", trt, ", AVALC) |>"),
    paste0("  group_by(", trt, ") |>"),
    "  mutate(pct = n / sum(n) * 100) |>",
    "  ungroup()",
    "",
    "# ORR = CR + PR",
    paste0("ard_orr <- adrs |>"),
    paste0('  filter(PARAMCD == "BOR") |>'),
    paste0("  group_by(", trt, ") |>"),
    '  summarise(responders = sum(AVALC %in% c("CR", "PR")),',
    '            n = n(), .groups = "drop") |>',
    "  mutate(rate = responders / n * 100)",
    ""
  ), collapse = "\n")
}

fct_codegen_ard_efficacy_cont <- function(grouping, var_configs) {
  trt <- grouping$trt_var
  paste(c(
    "# --- ARD: Continuous Efficacy ---",
    "",
    paste0("big_n <- adsl |> count(", trt, ', name = "N")'),
    "",
    "# Baseline stats",
    paste0("ard_baseline <- adeff |>"),
    paste0('  filter(ABLFL == "Y") |>'),
    paste0("  group_by(", trt, ", PARAMCD) |>"),
    "  summarise(n = n(), mean = mean(AVAL, na.rm = TRUE),",
    '    sd = sd(AVAL, na.rm = TRUE), .groups = "drop")',
    "",
    "# Change from baseline by visit",
    paste0("ard_cfb <- adeff |>"),
    paste0('  filter(!is.na(CHG), ABLFL != "Y") |>'),
    paste0("  group_by(", trt, ", PARAMCD, AVISIT) |>"),
    "  summarise(n = n(), mean_chg = mean(CHG, na.rm = TRUE),",
    '    sd_chg = sd(CHG, na.rm = TRUE), .groups = "drop")',
    ""
  ), collapse = "\n")
}

fct_codegen_ard_bds <- function(grouping, var_configs) {
  trt <- grouping$trt_var
  paste(c(
    "# --- ARD: BDS Results ---",
    "",
    paste0("big_n <- adsl |> count(", trt, ', name = "N")'),
    "",
    "# Results by parameter and visit",
    paste0("ard_results <- analysis_data |>"),
    paste0("  group_by(", trt, ", PARAMCD, PARAM, AVISIT) |>"),
    "  summarise(",
    "    n = n(),",
    "    mean = mean(AVAL, na.rm = TRUE),",
    "    sd = sd(AVAL, na.rm = TRUE),",
    "    median = median(AVAL, na.rm = TRUE),",
    "    q1 = quantile(AVAL, 0.25, na.rm = TRUE),",
    "    q3 = quantile(AVAL, 0.75, na.rm = TRUE),",
    "    min = min(AVAL, na.rm = TRUE),",
    "    max = max(AVAL, na.rm = TRUE),",
    '    .groups = "drop"',
    "  )",
    ""
  ), collapse = "\n")
}

fct_codegen_ard_shift <- function(grouping, var_configs) {
  trt <- grouping$trt_var
  paste(c(
    "# --- ARD: Shift Table ---",
    "",
    "# Cross-tabulation: baseline grade × post-baseline grade",
    paste0("ard_shift <- analysis_data |>"),
    paste0("  filter(!is.na(BNRIND), !is.na(ANRIND)) |>"),
    paste0("  count(", trt, ", PARAMCD, BNRIND, ANRIND)"),
    ""
  ), collapse = "\n")
}

fct_codegen_ard_marked <- function(grouping, var_configs) {
  trt <- grouping$trt_var
  paste(c(
    "# --- ARD: Marked Abnormalities ---",
    "",
    paste0("big_n <- adsl |> count(", trt, ', name = "N")'),
    "",
    paste0("ard_marked <- analysis_data |>"),
    paste0("  filter(!is.na(AVAL), !is.na(ANRHI)) |>"),
    "  mutate(marked_high = AVAL > 2 * ANRHI,",
    "         marked_low = AVAL < 0.5 * ANRLO) |>",
    paste0("  group_by(", trt, ", PARAMCD) |>"),
    "  summarise(",
    "    n_high = sum(marked_high, na.rm = TRUE),",
    "    n_low = sum(marked_low, na.rm = TRUE),",
    '    .groups = "drop"',
    "  )",
    ""
  ), collapse = "\n")
}

fct_codegen_fig_km <- function(grouping, var_configs) {
  trt <- grouping$trt_var
  paramcd <- var_configs$paramcd %||% "PFS"
  paste(c(
    "# --- Figure: Kaplan-Meier ---",
    "",
    paste0('tte_data <- adtte |> filter(PARAMCD == "', paramcd, '")'),
    paste0("km_fit <- survfit(Surv(AVAL, 1 - CNSR) ~ ", trt, ", data = tte_data)"),
    "",
    "# KM curves",
    "p_km <- ggplot() +",
    "  # KM step function built from survfit object",
    '  labs(x = "Time (months)", y = "Survival Probability",',
    paste0('       color = "', trt, '") +'),
    "  theme_minimal(base_size = 11) +",
    "  theme(legend.position = \"bottom\")",
    "",
    "# Risk table (optional)",
    "# p_risk <- ... (patchwork composition)",
    ""
  ), collapse = "\n")
}

fct_codegen_fig_waterfall <- function(grouping, var_configs) {
  trt <- grouping$trt_var
  paste(c(
    "# --- Figure: Waterfall ---",
    "",
    "# Best percent change from baseline",
    paste0("waterfall_data <- adrs |>"),
    paste0('  filter(PARAMCD == "OVRLRESP") |>'),
    paste0("  arrange(PCHG)"),
    "",
    "p <- ggplot(waterfall_data, aes(x = reorder(USUBJID, PCHG), y = PCHG, fill = AVALC)) +",
    "  geom_col() +",
    "  geom_hline(yintercept = c(-30, 20), linetype = \"dashed\", color = \"grey50\") +",
    '  labs(x = "Subject", y = "Best % Change from Baseline", fill = "BOR") +',
    "  theme_minimal(base_size = 11) +",
    '  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())',
    ""
  ), collapse = "\n")
}

fct_codegen_fig_forest <- function(grouping, var_configs) {
  trt <- grouping$trt_var
  paste(c(
    "# --- Figure: Forest Plot ---",
    "",
    "# Subgroup analyses — HR + 95% CI",
    "subgroups <- list(",
    '  list(var = "SEX", label = "Sex"),',
    '  list(var = "AGEGR1", label = "Age Group"),',
    '  list(var = "RACE", label = "Race")',
    ")",
    "",
    "forest_data <- lapply(subgroups, function(sg) {",
    paste0("  fit <- coxph(Surv(AVAL, 1 - CNSR) ~ ", trt, ", data = adtte,"),
    "    subset = !is.na(adtte[[sg$var]]))",
    "  tidy(fit, conf.int = TRUE, exponentiate = TRUE) |>",
    "    mutate(subgroup = sg$label)",
    "}) |> bind_rows()",
    "",
    "p <- ggplot(forest_data, aes(x = estimate, y = subgroup,",
    "    xmin = conf.low, xmax = conf.high)) +",
    "  geom_point() + geom_errorbarh(height = 0.2) +",
    "  geom_vline(xintercept = 1, linetype = \"dashed\") +",
    '  labs(x = "Hazard Ratio (95% CI)", y = NULL) +',
    "  theme_minimal(base_size = 11)",
    ""
  ), collapse = "\n")
}

fct_codegen_fig_swimmer <- function(grouping, var_configs) {
  paste(c(
    "# --- Figure: Swimmer Plot ---",
    "",
    "# Subject-level treatment timelines",
    "swimmer_data <- adtte |>",
    '  filter(PARAMCD == "OS") |>',
    "  arrange(AVAL)",
    "",
    "p <- ggplot(swimmer_data, aes(x = AVAL, y = reorder(USUBJID, AVAL))) +",
    "  geom_segment(aes(x = 0, xend = AVAL, yend = reorder(USUBJID, AVAL)),",
    '    linewidth = 3, color = "#4a6fa5") +',
    '  labs(x = "Time (months)", y = "Subject") +',
    "  theme_minimal(base_size = 11) +",
    '  theme(axis.text.y = element_blank())',
    ""
  ), collapse = "\n")
}

fct_codegen_listing <- function(template, var_configs) {
  cols <- var_configs$.listing_cols %||% c("USUBJID", "SITEID")
  sort_by <- var_configs$.sort_by %||% "USUBJID"

  paste(c(
    "# --- Listing ---",
    "",
    "listing <- analysis_data |>",
    paste0("  select(", paste(cols, collapse = ", "), ") |>"),
    paste0("  arrange(", sort_by, ")"),
    ""
  ), collapse = "\n")
}

fct_codegen_figure_render <- function(template, format_cfg) {
  paste(c(
    "",
    "# --- Save Figure ---",
    'ggsave("output.png", p, width = 10, height = 7, dpi = 300)',
    ""
  ), collapse = "\n")
}

fct_codegen_listing_render <- function(format_cfg) {
  paste(c(
    "",
    "# --- Render Listing ---",
    "listing |>",
    "  fr_table() |>",
    '  fr_render("output.rtf")',
    ""
  ), collapse = "\n")
}
