# R script code generator — pure R, no Shiny

fct_codegen <- function(data_cfg, grouping, var_configs, format_cfg,
                        combined_groups = NULL) {
  ir <- fct_build_ir(format_cfg, combined_groups)
  sections <- c(
    fct_codegen_header(),
    fct_codegen_data(data_cfg),
    fct_codegen_ard(grouping, var_configs),
    fct_codegen_format(ir),
    fct_codegen_render(ir)
  )
  paste(sections, collapse = "\n")
}

fct_codegen_header <- function() {
  paste0(
    "# =============================================================================\n",
    "# Generated by arcraft\n",
    "# Date: ", Sys.Date(), "\n",
    "# =============================================================================\n",
    "\n",
    "library(dplyr)\n",
    "library(cards)\n",
    "library(arframe)\n",
    "\n"
  )
}

fct_codegen_data <- function(data_cfg) {
  ds_name <- data_cfg$dataset %||% "adsl"
  path <- data_cfg$path %||% paste0("data/", ds_name, ".rds")
  pop_flag <- data_cfg$pop_flag
  pop_cond <- data_cfg$pop_condition

  lines <- c(
    "# --- Data ---",
    paste0(ds_name, ' <- readRDS("', path, '")')
  )

  if (!is.null(pop_flag) && nzchar(pop_flag)) {
    lines <- c(lines, paste0(ds_name, " <- ", ds_name, ' |> filter(', pop_flag, ' == "Y")'))
  } else if (!is.null(pop_cond) && nzchar(pop_cond)) {
    lines <- c(lines, paste0(ds_name, " <- ", ds_name, " |> filter(", pop_cond, ")"))
  }

  paste(c(lines, ""), collapse = "\n")
}

fct_codegen_ard <- function(grouping, var_configs) {
  trt_var <- grouping$trt_var
  trt_levels <- grouping$trt_levels
  include_total <- grouping$include_total %||% TRUE
  total_label <- grouping$total_label %||% "Total"
  analysis_vars <- grouping$analysis_vars
  combined_groups <- grouping$combined_groups %||% list()
  by_var <- grouping$by_var
  has_by <- !is.null(by_var) && nzchar(by_var %||% "")

  # Classify variables
  cont_vars <- character(0)
  cat_vars <- character(0)
  for (v in analysis_vars) {
    cfg <- var_configs[[v]] %||% list()
    vtype <- cfg$type %||% "categorical"
    if (vtype == "continuous") cont_vars <- c(cont_vars, v)
    else cat_vars <- c(cat_vars, v)
  }

  lines <- c("# --- ARD Construction ---", "")

  # Pre-factor categoricals if levels are specified
  for (v in cat_vars) {
    cfg <- var_configs[[v]] %||% list()
    if (!is.null(cfg$levels)) {
      lvls_str <- paste0('"', cfg$levels, '"', collapse = ", ")
      lines <- c(lines,
        paste0("adsl$", v, " <- factor(adsl$", v, ", levels = c(", lvls_str, "))"))
    }
  }
  if (length(cat_vars) > 0 && any(vapply(cat_vars, function(v) !is.null(var_configs[[v]]$levels), logical(1)))) {
    lines <- c(lines, "")
  }

  # Build ard_stack call
  lines <- c(lines, "raw_ard <- ard_stack(")
  lines <- c(lines, "  adsl,")

  if (length(cont_vars) > 0) {
    cont_str <- paste0(cont_vars, collapse = ", ")
    lines <- c(lines, paste0("  ard_continuous(variables = c(", cont_str, ")),"))
  }
  if (length(cat_vars) > 0) {
    cat_str <- paste0(cat_vars, collapse = ", ")
    lines <- c(lines, paste0("  ard_categorical(variables = c(", cat_str, ")),"))
  }

  lines <- c(lines, paste0("  .by = ", trt_var, ","))
  lines <- c(lines, paste0("  .overall = ", if (include_total) "TRUE" else "FALSE", ","))
  lines <- c(lines, "  .total_n = TRUE")
  lines <- c(lines, ")", "")

  # Combined groups: pool arms and bind
  for (cg in combined_groups) {
    arms_str <- paste0('"', cg$arms, '"', collapse = ", ")
    lines <- c(lines,
      paste0("# Combined group: ", cg$label),
      paste0("pooled <- adsl |> filter(", trt_var, " %in% c(", arms_str, ")) |>"),
      paste0('  mutate(', trt_var, ' = "', cg$label, '")'),
      ""
    )

    lines <- c(lines, "cg_ard <- ard_stack(")
    lines <- c(lines, "  pooled,")
    if (length(cont_vars) > 0) {
      lines <- c(lines, paste0("  ard_continuous(variables = c(", cont_str, ")),"))
    }
    if (length(cat_vars) > 0) {
      lines <- c(lines, paste0("  ard_categorical(variables = c(", cat_str, ")),"))
    }
    lines <- c(lines, paste0("  .by = ", trt_var, ","))
    lines <- c(lines, "  .total_n = TRUE")
    lines <- c(lines, ")")
    lines <- c(lines, "raw_ard <- bind_ard(raw_ard, cg_ard, .distinct = TRUE)", "")
  }

  # Build statistic format list for fr_wide_ard
  stat_lines <- codegen_build_stat_format(var_configs, analysis_vars, cont_vars, cat_vars)
  lines <- c(lines, stat_lines, "")

  # Build decimals list
  dec_lines <- codegen_build_decimals(var_configs, cont_vars, cat_vars)
  if (length(dec_lines) > 0) {
    lines <- c(lines, dec_lines, "")
  }

  # fr_wide_ard call
  overall_str <- if (include_total) paste0('"', total_label, '"') else "NULL"
  lines <- c(lines, "tbl_data <- arframe::fr_wide_ard(raw_ard,")
  lines <- c(lines, "  statistic = stat_fmt,")
  lines <- c(lines, paste0("  column = \"", trt_var, "\","))
  lines <- c(lines, paste0("  overall = ", overall_str))
  if (length(dec_lines) > 0) {
    # Replace the closing paren line to add decimals
    lines[length(lines)] <- paste0(lines[length(lines)], ",")
    lines <- c(lines, "  decimals = dec_map")
  }
  lines <- c(lines, ")", "")

  # Add var_label and var_type meta columns for downstream formatting
  lines <- c(lines,
    "# Add meta columns for formatting",
    "tbl_data$var_label <- NA_character_",
    "tbl_data$var_type <- NA_character_"
  )
  for (v in analysis_vars) {
    cfg <- var_configs[[v]] %||% list()
    vtype <- cfg$type %||% "categorical"
    var_label <- gsub('"', '\\\\"', cfg$label %||% v, fixed = TRUE)
    lines <- c(lines,
      paste0('tbl_data$var_label[tbl_data$variable == "', v, '"] <- "', var_label, '"'),
      paste0('tbl_data$var_type[tbl_data$variable == "', v, '"] <- "', vtype, '"'))
  }
  lines <- c(lines, "")

  # Reorder columns: meta first, then treatment columns
  lines <- c(lines,
    "# Reorder columns",
    'meta_cols <- c("variable", "var_label", "var_type", "stat_label")',
    "tbl_data <- tbl_data[, c(meta_cols, setdiff(names(tbl_data), meta_cols))]",
    ""
  )

  # BY variable: wrap the whole pipeline in a loop

  if (has_by) {
    by_levels <- grouping$by_levels

    # BY variable: wrap the full ard_stack in a lapply over by_levels
    lines <- c("# --- ARD Construction (by group: ", by_var, ") ---", "")

    # Pre-factor categoricals
    for (v in cat_vars) {
      cfg <- var_configs[[v]] %||% list()
      if (!is.null(cfg$levels)) {
        lvls_str <- paste0('"', cfg$levels, '"', collapse = ", ")
        lines <- c(lines,
          paste0("adsl$", v, " <- factor(adsl$", v, ", levels = c(", lvls_str, "))"))
      }
    }
    if (length(cat_vars) > 0 && any(vapply(cat_vars, function(v) !is.null(var_configs[[v]]$levels), logical(1)))) {
      lines <- c(lines, "")
    }

    lines <- c(lines, stat_lines, "")
    if (length(dec_lines) > 0) {
      lines <- c(lines, dec_lines, "")
    }

    by_lvls_str <- paste0('"', by_levels, '"', collapse = ", ")
    lines <- c(lines,
      paste0("by_levels <- c(", by_lvls_str, ")"),
      "",
      "tbl_data <- lapply(by_levels, function(bv) {",
      paste0("  sub <- adsl[adsl$", by_var, " == bv, , drop = FALSE]"),
      "",
      "  raw_ard <- ard_stack(",
      "    sub,"
    )
    if (length(cont_vars) > 0) {
      lines <- c(lines, paste0("    ard_continuous(variables = c(", paste0(cont_vars, collapse = ", "), ")),"))
    }
    if (length(cat_vars) > 0) {
      lines <- c(lines, paste0("    ard_categorical(variables = c(", paste0(cat_vars, collapse = ", "), ")),"))
    }
    lines <- c(lines,
      paste0("    .by = ", trt_var, ","),
      paste0("    .overall = ", if (include_total) "TRUE" else "FALSE", ","),
      "    .total_n = TRUE",
      "  )",
      ""
    )

    # Combined groups inside the loop
    for (cg in combined_groups) {
      arms_str <- paste0('"', cg$arms, '"', collapse = ", ")
      lines <- c(lines,
        paste0("  pooled <- sub |> filter(", trt_var, " %in% c(", arms_str, ")) |>"),
        paste0('    mutate(', trt_var, ' = "', cg$label, '")'),
        "  cg_ard <- ard_stack(",
        "    pooled,"
      )
      if (length(cont_vars) > 0) {
        lines <- c(lines, paste0("    ard_continuous(variables = c(", paste0(cont_vars, collapse = ", "), ")),"))
      }
      if (length(cat_vars) > 0) {
        lines <- c(lines, paste0("    ard_categorical(variables = c(", paste0(cat_vars, collapse = ", "), ")),"))
      }
      lines <- c(lines,
        paste0("    .by = ", trt_var, ","),
        "    .total_n = TRUE",
        "  )",
        "  raw_ard <- bind_ard(raw_ard, cg_ard, .distinct = TRUE)",
        ""
      )
    }

    lines <- c(lines,
      "  wide <- arframe::fr_wide_ard(raw_ard,",
      "    statistic = stat_fmt,",
      paste0("    column = \"", trt_var, "\","),
      paste0("    overall = ", overall_str)
    )
    if (length(dec_lines) > 0) {
      lines[length(lines)] <- paste0(lines[length(lines)], ",")
      lines <- c(lines, "    decimals = dec_map")
    }
    lines <- c(lines, "  )", "")

    # Add meta columns inside the loop
    lines <- c(lines,
      "  wide$var_label <- NA_character_",
      "  wide$var_type <- NA_character_"
    )
    for (v in analysis_vars) {
      cfg <- var_configs[[v]] %||% list()
      vtype <- cfg$type %||% "categorical"
      var_label <- gsub('"', '\\\\"', cfg$label %||% v, fixed = TRUE)
      lines <- c(lines,
        paste0('  wide$var_label[wide$variable == "', v, '"] <- "', var_label, '"'),
        paste0('  wide$var_type[wide$variable == "', v, '"] <- "', vtype, '"'))
    }

    lines <- c(lines,
      "  wide$group_value <- bv",
      "  wide",
      "}) |> bind_rows()",
      "",
      "# Reorder columns",
      'meta_cols <- c("group_value", "variable", "var_label", "var_type", "stat_label")',
      "tbl_data <- tbl_data[, c(meta_cols, setdiff(names(tbl_data), meta_cols))]",
      ""
    )
  }

  paste(lines, collapse = "\n")
}

# ── Codegen helpers for statistic format and decimals ──

codegen_build_stat_format <- function(var_configs, analysis_vars, cont_vars, cat_vars) {
  # Use shared builder to get the runtime list, then serialize to code
  fmt <- build_stat_format_from_config(var_configs, analysis_vars)
  var_entries <- character(0)

  for (v in analysis_vars) {
    val <- fmt[[v]]
    if (is.character(val) && length(val) > 1 && !is.null(names(val))) {
      # Named vector (continuous stats)
      parts <- vapply(names(val), function(lbl) {
        paste0('    `', lbl, '` = "', val[[lbl]], '"')
      }, character(1))
      entry <- paste0("  ", v, " = c(\n",
        paste(parts, collapse = ",\n"),
        "\n  )")
      var_entries <- c(var_entries, entry)
    } else {
      # Single string (categorical)
      var_entries <- c(var_entries, paste0('  ', v, ' = "', val, '"'))
    }
  }

  c(
    "stat_fmt <- list(",
    paste(var_entries, collapse = ",\n"),
    ")"
  )
}

codegen_build_decimals <- function(var_configs, cont_vars, cat_vars) {
  # Use shared builder to get the runtime list, then serialize to code
  all_vars <- c(cont_vars, cat_vars)
  dec <- build_decimals_from_config(var_configs, all_vars)

  if (length(dec) == 0) return(character(0))

  entries <- vapply(names(dec), function(v) {
    parts <- vapply(names(dec[[v]]), function(nm) {
      paste0(nm, " = ", dec[[v]][[nm]])
    }, character(1))
    paste0("  ", v, " = list(", paste(parts, collapse = ", "), ")")
  }, character(1))

  c(
    "dec_map <- list(",
    paste(entries, collapse = ",\n"),
    ")"
  )
}

fct_codegen_format <- function(ir, ard_cols = NULL) {
  lines <- c("# --- Table Formatting ---", "")

  # Build arframe pipeline
  lines <- c(lines,
    "tbl <- tbl_data |>",
    "  fr_table() |>"
  )

  # ── Columns (ir$cols) ──
  col_spec_lines <- c()

  # Hidden meta columns — always invisible
  # Use ard_cols to determine which meta columns exist, exclude the stub col
  stub_col <- ir$cols$stub$col %||% "stat_label"
  if (!is.null(ard_cols)) {
    meta_cols <- intersect(ir$cols$meta_hidden, ard_cols)
  } else {
    meta_cols <- intersect(ir$cols$meta_hidden, c("variable", "var_label", "var_type"))
  }
  meta_cols <- setdiff(meta_cols, stub_col)
  for (mc in meta_cols) {
    col_spec_lines <- c(col_spec_lines,
      paste0("    ", mc, " = fr_col(visible = FALSE)")
    )
  }

  # Stub column
  stub <- ir$cols$stub
  stub_args <- c("stub = TRUE")
  if (!is.null(stub$width)) stub_args <- c(stub_args, paste0("width = ", stub$width))
  # Check if user overrode alignment via per_col
  pc_stat <- ir$cols$per_col[[stub$col]]
  if (!is.null(pc_stat$align) && nzchar(pc_stat$align)) {
    stub_args <- c(stub_args, paste0('align = "', pc_stat$align, '"'))
  } else {
    stub_args <- c(stub_args, paste0('align = "', stub$align, '"'))
  }
  col_spec_lines <- c(col_spec_lines,
    paste0("    ", stub$col, " = fr_col(", paste(stub_args, collapse = ", "), ")")
  )

  # Per-column specs (excluding meta + stub)
  per_col <- ir$cols$per_col
  hdr_col_aligns <- ir$header$col_aligns
  all_spec_cols <- union(names(per_col), names(hdr_col_aligns))
  all_spec_cols <- setdiff(all_spec_cols, c(meta_cols, stub$col))

  for (cn in all_spec_cols) {
    pc <- per_col[[cn]] %||% list()
    ha <- hdr_col_aligns[[cn]]
    fc_args <- c()
    if (!is.null(pc$visible) && !pc$visible) fc_args <- c(fc_args, "visible = FALSE")
    if (!is.null(pc$width)) fc_args <- c(fc_args, paste0("width = ", pc$width))
    if (!is.null(pc$align) && nzchar(pc$align)) fc_args <- c(fc_args, paste0('align = "', pc$align, '"'))
    if (!is.null(ha)) fc_args <- c(fc_args, paste0('header_align = "', ha, '"'))
    if (length(fc_args) > 0) {
      cn_safe <- if (grepl(" ", cn, fixed = TRUE)) paste0("`", cn, "`") else cn
      col_spec_lines <- c(col_spec_lines,
        paste0("    ", cn_safe, " = fr_col(", paste(fc_args, collapse = ", "), ")"))
    }
  }

  # Global column options
  gl <- ir$cols$global
  col_args <- c()
  if (!is.null(gl$width_mode) && gl$width_mode != "auto") {
    col_args <- c(col_args, paste0('.width = "', gl$width_mode, '"'))
  }
  if (!is.null(gl$align)) col_args <- c(col_args, paste0('.align = "', gl$align, '"'))
  if (!is.null(gl$space_mode) && gl$space_mode != "indent") col_args <- c(col_args, paste0('.space_mode = "', gl$space_mode, '"'))
  if (isTRUE(gl$split)) col_args <- c(col_args, ".split = TRUE")
  if (isTRUE(gl$n_counts) && !is.null(gl$n_values) && length(gl$n_values) > 0) {
    n_entries <- paste0('"', names(gl$n_values), '" = ', gl$n_values, collapse = ", ")
    col_args <- c(col_args, paste0(".n = c(", n_entries, ")"))
  }
  if (!is.null(gl$n_format)) {
    # Keep literal \n in generated code
    fmt_str <- gl$n_format
    col_args <- c(col_args, paste0('.n_format = "', gsub('"', '\\\\"', fmt_str, fixed = TRUE), '"'))
  }

  if (length(col_spec_lines) > 0 || length(col_args) > 0) {
    all_inner <- c(col_spec_lines, paste0("    ", col_args))
    lines <- c(lines,
      "  fr_cols(",
      paste(all_inner, collapse = ",\n"),
      "  ) |>"
    )
  }

  # ── Titles (ir$titles) ──
  titles <- ir$titles$items
  title_defaults <- ir$titles$defaults
  if (length(titles) > 0) {
    title_items <- vapply(titles, function(t) {
      text <- gsub('"', '\\\\"', t$text %||% as.character(t), fixed = TRUE)
      bold <- isTRUE(t$bold)
      align <- t$align %||% "center"
      if (bold || align != "center") {
        args <- paste0('"', text, '"')
        if (bold) args <- paste0(args, ", bold = TRUE")
        if (align != "center") args <- paste0(args, ', align = "', align, '"')
        paste0("    list(", args, ")")
      } else {
        paste0('    "', text, '"')
      }
    }, character(1))
    title_extra <- ""
    if (!is.null(title_defaults$align) && title_defaults$align != "center") {
      title_extra <- paste0(title_extra, ', .align = "', title_defaults$align, '"')
    }
    if (isTRUE(title_defaults$bold)) {
      title_extra <- paste0(title_extra, ", .bold = TRUE")
    }
    lines <- c(lines,
      paste0("  fr_titles("),
      paste(title_items, collapse = ",\n"),
      paste0("  ", title_extra, ") |>")
    )
  }

  # ── Footnotes (ir$footnotes) ──
  fn_items <- ir$footnotes$items
  fn_texts <- list()
  if (length(fn_items) > 0) {
    fn_texts <- vapply(fn_items, function(f) {
      paste0('    "', gsub('"', '\\\\"', f$text %||% as.character(f), fixed = TRUE), '"')
    }, character(1))
  }
  if (length(fn_texts) > 0) {
    fn_extra <- ""
    if (isTRUE(ir$footnotes$separator)) fn_extra <- paste0(fn_extra, ", .separator = TRUE")
    if (ir$footnotes$placement != "every") {
      fn_extra <- paste0(fn_extra, ', .placement = "', ir$footnotes$placement, '"')
    }
    lines <- c(lines,
      "  fr_footnotes(",
      paste(fn_texts, collapse = ",\n"),
      paste0("  ", fn_extra, ") |>")
    )
  }

  # ── Header (ir$header) ──
  hdr <- ir$header
  hdr_args <- c()
  hdr_args <- c(hdr_args, paste0("bold = ", if (hdr$bold) "TRUE" else "FALSE"))
  hdr_args <- c(hdr_args, paste0('align = "', hdr$align, '"'))
  if (hdr$valign != "bottom") hdr_args <- c(hdr_args, paste0('valign = "', hdr$valign, '"'))
  if (!is.null(hdr$background) && nzchar(hdr$background)) hdr_args <- c(hdr_args, paste0('background = "', hdr$background, '"'))
  if (!is.null(hdr$color) && nzchar(hdr$color)) hdr_args <- c(hdr_args, paste0('color = "', hdr$color, '"'))
  if (!is.null(hdr$font_size)) hdr_args <- c(hdr_args, paste0("font_size = ", hdr$font_size))
  if (!is.null(hdr$repeat_on_page) && !isTRUE(hdr$repeat_on_page)) hdr_args <- c(hdr_args, "repeat_on_page = FALSE")
  lines <- c(lines, paste0("  fr_header(", paste(hdr_args, collapse = ", "), ") |>"))

  # ── Spans (ir$spans) ──
  for (sp in ir$spans) {
    if (nzchar(sp$label %||% "") && length(sp$cols) > 0) {
      cols_str <- paste0('c("', paste(sp$cols, collapse = '", "'), '")')
      level_str <- if (!is.null(sp$level) && sp$level > 1) paste0(", .level = ", sp$level) else ""
      lines <- c(lines, paste0('  fr_spans("', sp$label, '" = ', cols_str, level_str, ') |>'))
    }
  }

  # ── Page (ir$page) ──
  page <- ir$page
  if (!is.null(page)) {
    page_args <- c()
    if (!is.null(page$orientation)) page_args <- c(page_args, paste0('orientation = "', page$orientation, '"'))
    if (!is.null(page$paper)) page_args <- c(page_args, paste0('paper = "', page$paper, '"'))
    if (!is.null(page$font_family)) page_args <- c(page_args, paste0('font_family = "', page$font_family, '"'))
    if (!is.null(page$font_size)) page_args <- c(page_args, paste0("font_size = ", page$font_size))
    if (!is.null(page$margins)) {
      page_args <- c(page_args, paste0("margins = c(", paste(page$margins, collapse = ", "), ")"))
    }
    if (!is.null(page$col_gap) && page$col_gap != 4) page_args <- c(page_args, paste0("col_gap = ", page$col_gap))
    if (!is.null(page$continuation) && nzchar(page$continuation)) {
      page_args <- c(page_args, paste0('continuation = "', page$continuation, '"'))
    }
    if (!is.null(page$orphan_min) && page$orphan_min != 3L) page_args <- c(page_args, paste0("orphan_min = ", page$orphan_min))
    if (!is.null(page$widow_min) && page$widow_min != 3L) page_args <- c(page_args, paste0("widow_min = ", page$widow_min))
    if (length(page_args) > 0) {
      lines <- c(lines, paste0("  fr_page(", paste(page_args, collapse = ", "), ") |>"))
    }
  }

  # ── Rules (ir$rules) ──
  rules <- ir$rules
  if (!is.null(rules$hline_preset)) {
    hline_args <- paste0('"', rules$hline_preset, '"')
    if (rules$line_width != "thin") {
      hline_args <- paste0(hline_args, ', width = "', rules$line_width, '"')
    }
    if (rules$line_color != "#000000") {
      hline_args <- paste0(hline_args, ', color = "', rules$line_color, '"')
    }
    if (rules$line_style != "solid") {
      hline_args <- paste0(hline_args, ', linestyle = "', rules$line_style, '"')
    }
    lines <- c(lines, paste0("  fr_hlines(", hline_args, ") |>"))
  }
  if (!is.null(rules$vline_preset) && rules$vline_preset != "none") {
    lines <- c(lines, paste0('  fr_vlines("', rules$vline_preset, '") |>'))
  }

  # ── Rows (ir$rows) — only emit column refs that exist in ARD ──
  rows <- ir$rows
  col_exists <- function(col) is.null(ard_cols) || col %in% ard_cols
  row_args <- c()
  has_group_by <- !is.null(rows$group_by) && col_exists(rows$group_by)
  has_group_label <- !is.null(rows$group_label) && col_exists(rows$group_label)
  has_page_by <- !is.null(rows$page_by) && col_exists(rows$page_by)
  # group_by: list form if group_label is set, otherwise simple string
  if (has_group_by && has_group_label) {
    row_args <- c(row_args, paste0('group_by = list(cols = "', rows$group_by, '", label = "', rows$group_label, '")'))
  } else if (has_group_by) {
    row_args <- c(row_args, paste0('group_by = "', rows$group_by, '"'))
  }
  if (!is.null(rows$blank_after) && col_exists(rows$blank_after))
    row_args <- c(row_args, paste0('blank_after = "', rows$blank_after, '"'))
  # page_by: list form if page_by_visible is FALSE, otherwise simple string
  if (has_page_by && isFALSE(rows$page_by_visible)) {
    row_args <- c(row_args, paste0('page_by = list(cols = "', rows$page_by, '", visible = FALSE)'))
  } else if (has_page_by) {
    row_args <- c(row_args, paste0('page_by = "', rows$page_by, '"'))
  }
  if (has_group_by && isFALSE(rows$group_keep))
    row_args <- c(row_args, "group_keep = FALSE")
  if (!is.null(rows$indent_by) && col_exists(rows$indent_by))
    row_args <- c(row_args, paste0('indent_by = "', rows$indent_by, '"'))
  if (!is.null(rows$sort_by)) {
    valid_sort <- rows$sort_by[vapply(rows$sort_by, col_exists, logical(1))]
    if (length(valid_sort) > 0)
      row_args <- c(row_args, paste0('sort_by = c("', paste(valid_sort, collapse = '", "'), '")'))
  }
  if (!is.null(rows$suppress)) {
    valid_cols <- rows$suppress[vapply(rows$suppress, col_exists, logical(1))]
    if (length(valid_cols) > 0)
      row_args <- c(row_args, paste0('suppress = c("', paste(valid_cols, collapse = '", "'), '")'))
  }
  if (isTRUE(rows$wrap)) row_args <- c(row_args, "wrap = TRUE")
  if (length(row_args) > 0) {
    lines <- c(lines, paste0("  fr_rows(", paste(row_args, collapse = ", "), ") |>"))
  }

  # ── Page chrome (ir$pagehead, ir$pagefoot) ──
  ph <- ir$pagehead
  if (any(nzchar(c(ph$left, ph$center, ph$right)))) {
    ph_args <- c()
    if (nzchar(ph$left)) ph_args <- c(ph_args, paste0('left = "', ph$left, '"'))
    if (nzchar(ph$center)) ph_args <- c(ph_args, paste0('center = "', ph$center, '"'))
    if (nzchar(ph$right)) ph_args <- c(ph_args, paste0('right = "', ph$right, '"'))
    lines <- c(lines, paste0("  fr_pagehead(", paste(ph_args, collapse = ", "), ") |>"))
  }

  pf <- ir$pagefoot
  if (any(nzchar(c(pf$left, pf$center, pf$right)))) {
    pf_args <- c()
    if (nzchar(pf$left)) pf_args <- c(pf_args, paste0('left = "', pf$left, '"'))
    if (nzchar(pf$center)) pf_args <- c(pf_args, paste0('center = "', pf$center, '"'))
    if (nzchar(pf$right)) pf_args <- c(pf_args, paste0('right = "', pf$right, '"'))
    lines <- c(lines, paste0("  fr_pagefoot(", paste(pf_args, collapse = ", "), ") |>"))
  }

  # ── Spacing (ir$spacing) ──
  sp <- ir$spacing
  sp_args <- c()
  if (sp$titles_after != 1L) sp_args <- c(sp_args, paste0("titles_after = ", sp$titles_after))
  if (sp$footnotes_before != 1L) sp_args <- c(sp_args, paste0("footnotes_before = ", sp$footnotes_before))
  if (sp$pagehead_after != 0L) sp_args <- c(sp_args, paste0("pagehead_after = ", sp$pagehead_after))
  if (sp$pagefoot_before != 0L) sp_args <- c(sp_args, paste0("pagefoot_before = ", sp$pagefoot_before))
  if (!is.null(sp$page_by_after)) sp_args <- c(sp_args, paste0("page_by_after = ", sp$page_by_after))
  if (length(sp_args) > 0) {
    lines <- c(lines, paste0("  fr_spacing(", paste(sp_args, collapse = ", "), ") |>"))
  }

  # ── Styles (ir$styles) ──
  stys <- ir$styles
  if (length(stys) > 0) {
    style_items <- c()
    for (sname in names(stys)) {
      s <- stys[[sname]]
      if (s$type == "row_match") {
        # fr_rows_matches + fr_row_style
        match_args <- paste0('fr_rows_matches("', s$col, '"')
        if (!is.null(s$pattern)) match_args <- paste0(match_args, ', pattern = "', s$pattern, '"')
        if (!is.null(s$value))   match_args <- paste0(match_args, ', value = "', s$value, '"')
        match_args <- paste0(match_args, ")")
        rs_args <- c(paste0("rows = ", match_args))
        if (isTRUE(s$bold))       rs_args <- c(rs_args, "bold = TRUE")
        if (!is.null(s$background)) rs_args <- c(rs_args, paste0('background = "', s$background, '"'))
        if (!is.null(s$color))     rs_args <- c(rs_args, paste0('color = "', s$color, '"'))
        if (!is.null(s$italic))   rs_args <- c(rs_args, "italic = TRUE")
        style_items <- c(style_items,
          paste0("    fr_row_style(", paste(rs_args, collapse = ", "), ")"))
      } else if (s$type == "conditional") {
        si_args <- c(paste0('condition = ', s$condition))
        if (!is.null(s$cols))     si_args <- c(si_args, paste0('cols = "', s$cols, '"'))
        if (!is.null(s$apply_to)) si_args <- c(si_args, paste0('apply_to = "', s$apply_to, '"'))
        if (isTRUE(s$bold))       si_args <- c(si_args, "bold = TRUE")
        if (!is.null(s$background)) si_args <- c(si_args, paste0('background = "', s$background, '"'))
        if (!is.null(s$color))     si_args <- c(si_args, paste0('color = "', s$color, '"'))
        style_items <- c(style_items,
          paste0("    fr_style_if(", paste(si_args, collapse = ", "), ")"))
      } else if (s$type == "row") {
        rs_args <- c()
        if (!is.null(s$match))  rs_args <- c(rs_args, paste0('rows = "', s$match, '"'))
        if (isTRUE(s$bold))     rs_args <- c(rs_args, "bold = TRUE")
        if (!is.null(s$background)) rs_args <- c(rs_args, paste0('background = "', s$background, '"'))
        if (!is.null(s$color))     rs_args <- c(rs_args, paste0('color = "', s$color, '"'))
        style_items <- c(style_items,
          paste0("    fr_row_style(", paste(rs_args, collapse = ", "), ")"))
      }
    }
    if (length(style_items) > 0) {
      lines <- c(lines,
        "  fr_styles(",
        paste(style_items, collapse = ",\n"),
        "  ) |>"
      )
    }
  }

  # Strip trailing |> from last line and close
  lines[length(lines)] <- gsub(" \\|>$", "", lines[length(lines)])

  paste(lines, collapse = "\n")
}

# ── AE data loading codegen ──
fct_codegen_data_ae <- function(data_cfg) {
  pop_flag <- data_cfg$pop_flag
  pop_cond <- data_cfg$pop_condition
  adsl_path <- data_cfg$path %||% "data/adsl.rds"
  adae_path <- gsub("adsl", "adae", adsl_path, fixed = TRUE)

  lines <- c(
    "# --- Data ---",
    paste0('adsl <- readRDS("', adsl_path, '")'),
    paste0('adae <- readRDS("', adae_path, '")')
  )

  if (!is.null(pop_flag) && nzchar(pop_flag)) {
    lines <- c(lines,
      paste0('adsl <- adsl |> filter(', pop_flag, ' == "Y")'),
      paste0('adae <- adae |> filter(', pop_flag, ' == "Y")')
    )
  } else if (!is.null(pop_cond) && nzchar(pop_cond)) {
    lines <- c(lines,
      paste0("adsl <- adsl |> filter(", pop_cond, ")"),
      paste0("adae <- adae |> filter(", pop_cond, ")")
    )
  }

  paste(c(lines, ""), collapse = "\n")
}

# ── AE Overall codegen ──
fct_codegen_ard_ae_overall <- function(grouping, var_configs) {
  trt_var <- grouping$trt_var
  trt_levels <- grouping$trt_levels
  include_total <- grouping$include_total %||% TRUE
  total_label <- grouping$total_label %||% "Total"
  filter_flag <- var_configs$filter_flag %||% "TRTEMFL"

  lines <- c(
    "# --- ARD Construction: AE Overall Summary ---",
    "",
    "# Build subject-level flag dataset",
    paste0('adae_teae <- adae |> filter(', filter_flag, ' == "Y")'),
    "",
    "ae_subj <- adsl |>",
    paste0("  select(USUBJID, ", trt_var, ") |>"),
    "  left_join(",
    "    adae_teae |>",
    "      group_by(USUBJID) |>",
    "      summarise(",
    '        any_teae    = any(TRTEMFL == "Y", na.rm = TRUE),',
    '        any_sae     = any(AESER == "Y", na.rm = TRUE),',
    '        any_death   = any(AESDTH == "Y", na.rm = TRUE),',
    '        any_related = any(AEREL %in% c("POSSIBLE", "PROBABLE"), na.rm = TRUE),',
    "        max_sev     = if (all(is.na(AESEV))) NA_character_",
    '                      else c("MILD", "MODERATE", "SEVERE")[',
    '                        max(match(AESEV, c("MILD", "MODERATE", "SEVERE")),',
    "                            na.rm = TRUE)],",
    "        .groups = \"drop\"",
    "      ),",
    '    by = "USUBJID"',
    "  ) |>",
    "  mutate(",
    "    across(c(any_teae, any_sae, any_death, any_related),",
    "           ~ replace_na(.x, FALSE)),",
    '    max_sev = factor(max_sev, levels = c("MILD", "MODERATE", "SEVERE"))',
    "  )",
    "",
    "ae_ard <- ard_stack(",
    "  data = ae_subj,",
    paste0("  .by = ", trt_var, ","),
    "  ard_dichotomous(",
    "    variables = c(any_teae, any_sae, any_death, any_related),",
    "    value = list(",
    "      any_teae = TRUE, any_sae = TRUE,",
    "      any_death = TRUE, any_related = TRUE",
    "    )",
    "  ),",
    '  ard_categorical(variables = "max_sev"),',
    paste0("  .overall = ", if (include_total) "TRUE" else "FALSE"),
    ")",
    "",
    "tbl_data <- fr_wide_ard(",
    "  ae_ard,",
    "  statistic = list(",
    '    dichotomous = "{n} ({p}%)",',
    '    categorical = "{n} ({p}%)"',
    "  ),",
    paste0('  column = "', trt_var, '",'),
    "  decimals = c(p = 1),",
    paste0("  overall = ", if (include_total) paste0('"', total_label, '"') else "NULL", ","),
    "  label = c(",
    '    any_teae    = "Any TEAE",',
    '    any_sae     = "Any Serious AE (SAE)",',
    '    any_death   = "Any AE Leading to Death",',
    '    any_related = "Any AE Related to Study Drug",',
    '    max_sev     = "Maximum Severity"',
    "  )",
    ")",
    "",
    "# Add category column for grouping",
    "flag_labels <- c(\"Any TEAE\", \"Any Serious AE (SAE)\",",
    "                  \"Any AE Leading to Death\", \"Any AE Related to Study Drug\")",
    "tbl_data$category <- ifelse(",
    "  tbl_data$variable %in% c(\"any_teae\", \"any_sae\", \"any_death\", \"any_related\") |",
    "    tbl_data$stat_label %in% flag_labels,",
    '  "",',
    '  "Maximum Severity"',
    ")",
    ""
  )

  paste(lines, collapse = "\n")
}

# ── AE Hierarchical codegen (dynamic N-level) ──
fct_codegen_ard_ae_hierarchy <- function(grouping, var_configs) {
  trt_var <- grouping$trt_var
  include_total <- grouping$include_total %||% TRUE
  total_label <- grouping$total_label %||% "Total"
  filter_flag <- var_configs$filter_flag %||% "TRTEMFL"
  hierarchy_vars <- grouping$analysis_vars
  sort_order <- var_configs$sort_order %||% "frequency"
  include_overall <- var_configs$include_overall %||% TRUE
  overall_label <- var_configs$overall_label %||% "Subjects with at Least One TEAE"

  vars_str <- paste(hierarchy_vars, collapse = ", ")

  sort_line <- if (sort_order == "frequency") {
    '  sort_ard_hierarchical(sort = "descending")'
  } else if (sort_order == "alpha_freq") {
    '  sort_ard_hierarchical(sort = "alphanumeric")'
  } else {
    NULL
  }

  lines <- c(
    "# --- ARD Construction: AE Hierarchy ---",
    "",
    paste0('adae_teae <- adae |> filter(', filter_flag, ' == "Y")'),
    "",
    "ae_ard <- ard_stack_hierarchical(",
    "  data = adae_teae,",
    paste0("  variables = c(", vars_str, "),"),
    paste0("  by = ", trt_var, ","),
    "  denominator = adsl,",
    "  id = USUBJID,",
    paste0("  overall = ", if (include_total) "TRUE" else "FALSE", ","),
    paste0("  over_variables = ", if (include_overall) "TRUE" else "FALSE"),
    ")"
  )

  if (!is.null(sort_line)) {
    lines[length(lines)] <- sub("\\)$", ") |>", lines[length(lines)])
    lines <- c(lines, sort_line)
  }

  label_lines <- if (include_overall) {
    c(
      "  label = c(",
      paste0('    "..ard_hierarchical_overall.." = "', overall_label, '"'),
      "  )"
    )
  } else {
    NULL
  }

  lines <- c(lines,
    "",
    "tbl_data <- fr_wide_ard(",
    "  ae_ard,",
    '  statistic = "{n} ({p}%)",',
    paste0('  column = "', trt_var, '",'),
    "  decimals = c(p = 1),",
    paste0("  overall = ", if (include_total) paste0('"', total_label, '"') else "NULL",
      if (!is.null(label_lines)) "," else ""),
    label_lines,
    ")",
    ""
  )

  paste(lines, collapse = "\n")
}

fct_codegen_render <- function(ir) {
  ext <- switch(ir$output_format,
    pdf = "pdf",
    html = "html",
    tex = "tex",
    "rtf"
  )
  paste(c(
    "",
    "# --- Render ---",
    paste0('tbl |> fr_render("output.', ext, '")'),
    ""
  ), collapse = "\n")
}
